In [1]:
import os
import sys
sys.path.append("../financial_rag/")

from services.load_documents import load_documents

In [2]:
%load_ext autoreload
%autoreload 2

In [77]:
import requests
import json

def load_json_data(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3",
        "Accept": "application/json",
    }

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Raises an HTTPError for bad responses
        json_data = response.json()
        return json_data
    except requests.RequestException as e:
        print(f"Error fetching JSON data: {e}")
        return None



def load_ticks():
    # Opening JSON file
    with open('../data/tickers.json', 'r') as openfile:
    
        # Reading from json file
        tickers = json.load(openfile)
    return tickers

In [ ]:
pdf_filename = "document.pdf"

# This command converts the HTML file to PDF using pdfkit
pdfkit.from_file(html_filename, pdf_filename)

print(f"PDF file saved as {pdf_filename}")

In [67]:
acc = load_json_data("https://data.sec.gov/api/xbrl/frames/us-gaap/AccountsPayableCurrent/USD/CY2019Q1I.json")

In [69]:
acc.keys()

dict_keys(['taxonomy', 'tag', 'ccp', 'uom', 'label', 'description', 'pts', 'data'])

In [72]:
pd.DataFrame(acc["data"])

,accn,cik,entityName,loc,end,val
0,0001104659-19-016320,1750,AAR CORP.,US-IL,2019-02-28,218600000
1,0001264931-19-000067,1961,WORLDS INC.,US-MA,2019-03-31,797908
2,0001026608-19-000026,2098,ACME UNITED CORP,US-CT,2019-03-31,5672000
3,0000002178-19-000020,2178,"ADAMS RESOURCES & ENERGY, INC.",US-TX,2019-03-31,133325000
4,0001654954-19-005464,2186,BK Technologies Corporation,US-FL,2019-03-31,6197000
...,...,...,...,...,...,...
3385,0001193125-19-175022,1766368,"Mayville Engineering Company, Inc.",US-WI,2019-03-31,50327000
3386,0001493152-20-012020,1770202,HANTANG CULTURE & EDUCATION HOLDING GROUP LTD,CN-,2019-03-31,4129
3387,0001773383-20-000053,1773383,"DYNATRACE, INC.",US-MA,2019-03-31,6559000
3388,0001099910-19-000059,1776048,"AmeraMex International, Inc.",US-CA,2019-03-31,2565403
3389,0001104659-21-115144,1782309,Skillful Craftsman Education Technology Ltd,-,2019-03-31,10025

In [76]:
import requests
import pdfkit

# Step 1: Download the .htm file
url = "https://www.sec.gov/Archives/edgar/data/320193/000114036124038601/ny20033611x3_8k.htm"
html_filename = "document.html"

headers = {
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3",
        "Accept": "application/json",}

response = requests.get(url, headers=headers)

# Save the .htm content as an HTML file
if response.status_code == 200:
    with open(html_filename, 'w', encoding='utf-8') as file:
        file.write(response.text)
    print(f"HTML file saved as {html_filename}")
else:
    print(f"Failed to download HTML. Status code: {response.status_code}")


# Step 2: Convert the HTML file to PDF
pdf_filename = "document.pdf"

# This command converts the HTML file to PDF using pdfkit
pdfkit.from_file(html_filename, pdf_filename)

print(f"PDF file saved as {pdf_filename}")

Failed to download HTML. Status code: 403

OSError: No wkhtmltopdf executable found: "b''"
If this file exists please check that this process can read it or you can pass path to it manually in method call, check README. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf

In [65]:
import requests

# Define the URL and the filename
url = "https://www.sec.gov/Archives/edgar/data/320193/000114036124038601/ny20033611x3_8k.htm"
output_file = "document.html"  # Save the file as .html

# Set up headers with User-Agent to avoid 403 errors
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
    "Accept": "application/json",
}

# Fetch the content
response = requests.get(url, headers=headers)

# Check if the request was successful
if response.status_code == 200:
    # Save the content to an .html file
    with open(output_file, 'w', encoding='utf-8') as file:
        file.write(response.text)
    print(f"File saved as {output_file}")
else:
    print(f"Failed to download file. Status code: {response.status_code}")

Failed to download file. Status code: 403

In [30]:
ticks = load_ticks()

In [31]:
ticks["aapl"]

'0000320193'

In [32]:
cik_num = ticks["aapl"]
# URL of the JSON data
url = f"https://data.sec.gov/submissions/CIK{cik_num}.json"

# Load the JSON data
data = load_json_data(url)
if data:
    print(data)

{'cik': '320193', 'entityType': 'operating', 'sic': '3571', 'sicDescription': 'Electronic Computers', 'insiderTransactionForOwnerExists': 0, 'insiderTransactionForIssuerExists': 1, 'name': 'Apple Inc.', 'tickers': ['AAPL'], 'exchanges': ['Nasdaq'], 'ein': '942404110', 'description': '', 'website': '', 'investorWebsite': '', 'category': 'Large accelerated filer', 'fiscalYearEnd': '0928', 'stateOfIncorporation': 'CA', 'stateOfIncorporationDescription': 'CA', 'addresses': {'mailing': {'street1': 'ONE APPLE PARK WAY', 'street2': None, 'city': 'CUPERTINO', 'stateOrCountry': 'CA', 'zipCode': '95014', 'stateOrCountryDescription': 'CA'}, 'business': {'street1': 'ONE APPLE PARK WAY', 'street2': None, 'city': 'CUPERTINO', 'stateOrCountry': 'CA', 'zipCode': '95014', 'stateOrCountryDescription': 'CA'}}, 'phone': '(408) 996-1010', 'flags': '', 'formerNames': [{'name': 'APPLE INC', 'from': '2007-01-10T00:00:00.000Z', 'to': '2019-08-05T00:00:00.000Z'}, {'name': 'APPLE COMPUTER INC', 'from': '1994-01-26T00:00:00.000Z', 'to': '2007-01-04T00:00:00.000Z'}, {'name': 'APPLE COMPUTER INC/ FA', 'from': '1997-07-28T00:00:00.000Z', 'to': '1997-07-28T00:00:00.000Z'}], 'filings': {'recent': {'accessionNumber': ['0001140361-24-038601', '0001140361-24-038403', '0000320193-24-000088', '0000320193-24-000086', '0000320193-24-000084', '0001950047-24-005824', '0000320193-24-000081', '0000320193-24-000080', '0000320193-24-000075', '0001921094-24-000702', '0000320193-24-000073', '0000000000-24-005673', '0000320193-24-000071', '0001140361-24-024352', '0000320193-24-000069', '0000320193-24-000067', '0000320193-24-000061', '0000320193-24-000058', '0000320193-24-000056', '0000320193-24-000055', '0001958244-24-001666', '0001973141-24-000220', '0001140361-24-018378', '0000320193-24-000052', '0000320193-24-000051', '0000320193-24-000050', '0000320193-24-000049', '0000320193-24-000048', '0001973141-24-000208', '0001950047-24-002876', '0001959173-24-002769', '0000000000-24-003505', '0001140361-24-015633', '0000320193-24-000042', '0000000000-24-002512', '0000320193-24-000039', '0000320193-24-000038', '0000320193-24-000037', '0000320193-24-000036', '0000320193-24-000035', '0000320193-24-000034', '0000320193-24-000033', '0000320193-24-000032', '0001921094-24-000276', '0001140361-24-010155', '0001193125-24-036431', '0001104659-24-020009', '0001086364-24-006980', '0001096906-24-000181', '0000320193-24-000022', '0000320193-24-000021', '0000320193-24-000020', '0000320193-24-000019', '0000320193-24-000018', '0000320193-24-000017', '0000320193-24-000016', '0000320193-24-000015', '0001096906-24-000156', '0001096906-24-000151', '0000320193-24-000006', '0000320193-24-000005', '0001096906-24-000149', '0001096906-24-000148', '0001096906-24-000147', '0001096906-24-000145', '0001214659-24-001028', '0001354457-24-000017', '0001308179-24-000011', '0001308179-24-000010', '0000320193-23-000113', '0000320193-23-000111', '0000320193-23-000109', '0000320193-23-000106', '0000320193-23-000104', '0000320193-23-000099', '0000320193-23-000097', '0000320193-23-000096', '0001958244-23-001819', '0001958244-23-001817', '0001973141-23-000238', '0000320193-23-000093', '0000320193-23-000092', '0000320193-23-000091', '0000320193-23-000090', '0000320193-23-000089', '0000320193-23-000088', '0001950047-23-004374', '0001973141-23-000233', '0001959173-23-004170', '0000320193-23-000081', '0000320193-23-000079', '0001973141-23-000171', '0000320193-23-000077', '0000320193-23-000075', '0000320193-23-000070', '0000320193-23-000068', '0000320193-23-000066', '0001140361-23-023909', '0001140361-23-023700', '0001140361-23-023544', '0001140361-23-023333', '0000320193-23-000064', '0000320193-23-000063', '0000320193-23-000057', '0000320193-23-000055', '0001958244-23-000454', '0000320193-23-000053', '0001958244-23-000440', '0000320193-23-000051', '0000320193-23-000050', '0000320193-23-000049', '0000320193-23-000048', '0000320193-23-000047', '0000320193-23-000040', '0001140361-23-012065', '0000320193-23-000038', '0000320193-23-000037', '0000320193-23-000036', '0000320193-23-000035', '0000320193-23-000034', '0000320193-23-000033', '0000320193-23-000032', '0000320193-23-000031', '0001140361-23-011192', '0001096906-23-000438', '0001096906-23-000437', '0001214659-23-002862', '0001096906-23-000372', '0001193125-23-038262', '0001104659-23-015055', '0001306550-23-008266', '0000320193-23-000022', '0000320193-23-000021', '0000320193-23-000020', '0000320193-23-000019', '0000320193-23-000018', '0000320193-23-000017', '0000320193-23-000016', '0000320193-23-000015', '0001140361-23-004439', '0000320193-23-000006', '0000320193-23-000005', '0001214659-23-001246', '0001214659-23-000970', '0001308179-23-000020', '0001308179-23-000019', '0000320193-22-000113', '0001354457-22-000638', '0001193125-22-278435', '0000320193-22-000111', '0000320193-22-000108', '0000320193-22-000107', '0000320193-22-000102', '0000320193-22-000101', '0000320193-22-000097', '0000320193-22-000095', '0000320193-22-000096', '0000320193-22-000098', '0000320193-22-000090', '0000320193-22-000089', '0000320193-22-000088', '0000320193-22-000087', '0000320193-22-000086', '0000320193-22-000085', '0000320193-22-000078', '0000320193-22-000076', '0001193125-22-225365', '0000320193-22-000074', '0001193125-22-214914', '0000320193-22-000072', '0001193125-22-210056', '0001193125-22-209084', '0001193125-22-207773', '0000320193-22-000070', '0000320193-22-000069', '0000320193-22-000063', '0000320193-22-000061', '0001193125-22-128368', '0001193125-22-128361', '0001193125-22-128354', '0000320193-22-000059', '0000320193-22-000058', '0000320193-22-000053', '0000320193-22-000052', '0000320193-22-000049', '0000320193-22-000048', '0000320193-22-000047', '0000320193-22-000046', '0000320193-22-000041', '0000320193-22-000040', '0000320193-22-000039', '0000320193-22-000038', '0000320193-22-000037', '0000320193-22-000036', '0000320193-22-000035', '0000320193-22-000034', '0001193125-22-066169', '0001193125-22-032738', '0001104659-22-016224', '0001214659-22-002092', '0000320193-22-000025', '0000320193-22-000023', '0000320193-22-000022', '0000320193-22-000021', '0000320193-22-000020', '0000320193-22-000019', '0000320193-22-000018', '0000320193-22-000017', '0000320193-22-000016', '0001214659-22-001589', '0001214659-22-001473', '0000834237-22-004076', '0001214659-22-001295', '0000320193-22-000007', '0000320193-22-000006', '0001377739-22-000005', '0001193125-22-003593', '0001193125-22-003583', '0000320193-21-000114', '0000320193-21-000112', '0000320193-21-000111', '0001193125-21-328151', '0000320193-21-000108', '0001193125-21-312274', '0001193125-21-311635', '0000320193-21-000105', '0000320193-21-000104', '0000320193-21-000099', '0000320193-21-000097', '0000320193-21-000096', '0000320193-21-000093', '0000320193-21-000092', '0000320193-21-000091', '0000320193-21-000090', '0000320193-21-000085', '0000320193-21-000084', '0000320193-21-000083', '0000320193-21-000082', '0000320193-21-000081', '0000320193-21-000080', '0000320193-21-000073', '0000320193-21-000071', '0000320193-21-000069', '0001193125-21-237787', '0000320193-21-000067', '0001193125-21-231584', '0001193125-21-229470', '0001193125-21-228285', '0001193125-21-225983', '0000320193-21-000065', '0000320193-21-000063', '0000320193-21-000060', '0000320193-21-000059', '0000320193-21-000056', '0000320193-21-000055', '0000320193-21-000050', '0000320193-21-000049', '0000320193-21-000046', '0000320193-21-000045', '0000320193-21-000044', '0000320193-21-000040', '0000320193-21-000039', '0000320193-21-000038', '0000320193-21-000037', '0000320193-21-000036', '0000320193-21-000035', '0000320193-21-000034', '0001193125-21-054710', '0001214659-21-002046', '0001193125-21-044816', '0001193125-21-036337', '0001104659-21-017199', '0001193125-21-032394', '0000834237-21-007542', '0000320193-21-000026', '0000320193-21-000025', '0000320193-21-000024', '0000320193-21-000023', '0000320193-21-000022', '0000320193-21-000021', '0000320193-21-000020', '0000320193-21-000019', '0001193125-21-025910', '0001193125-21-024892', '0001193125-21-023836', '0000320193-21-000010', '0000320193-21-000009', '0000320193-21-000004', '0000320193-21-000003', '0001193125-21-001989', '0001193125-21-001987', '0001193125-21-001982', '0000320193-20-000101', '0000320193-20-000099', '0000320193-20-000096', '0000320193-20-000094', '0000320193-20-000090', '0000320193-20-000089', '0000320193-20-000086', '0000320193-20-000084', '0000320193-20-000083', '0000320193-20-000082', '0000320193-20-000078', '0000320193-20-000077', '0000320193-20-000076', '0000320193-20-000075', '0000320193-20-000074', '0000320193-20-000073', '0000320193-20-000066', '0000320193-20-000064', '0001193125-20-225672', '0001193125-20-220410', '0001193125-20-219289', '0001193125-20-218350', '0001193125-20-213158', '0000320193-20-000062', '0000320193-20-000060', '0000320193-20-000056', '0001193125-20-139112', '0001193125-20-133777', '0001193125-20-132661', '0001193125-20-131780', '0000320193-20-000052', '0000320193-20-000054', '0000320193-20-000050', '0000320193-20-000045', '0000320193-20-000044', '0000320193-20-000041', '0000320193-20-000039', '0000320193-20-000038', '0000320193-20-000035', '0000320193-20-000034', '0000320193-20-000033', '0000320193-20-000032', '0000320193-20-000031', '0000320193-20-000030', '0001193125-20-050884', '0001193125-20-039203', '0001193125-20-038381', '0001104659-20-018528', '0000834237-20-008795', '0001193125-20-026822', '0000320193-20-000023', '0000320193-20-000022', '0000320193-20-000021', '0000320193-20-000020', '0000320193-20-000019', '0000320193-20-000018', '0000320193-20-000011', '0000320193-20-000010', '0000320193-20-000008', '0001214659-20-000610', '0001387131-20-000386', '0001193125-20-001452', '0001193125-20-001450', '0000320193-20-000002', '0001354457-19-000604', '0001193125-19-292825', '0001193125-19-292676', '0000320193-19-000123', '0001193125-19-288412', '0000320193-19-000121', '0001193125-19-287351', '0001193125-19-286514', '0001193125-19-280516', '0000320193-19-000119', '0000320193-19-000117', '0000320193-19-000113', '0000320193-19-000112', '0000320193-19-000109', '0000320193-19-000107', '0000320193-19-000106', '0000320193-19-000103', '0000320193-19-000102', '0000320193-19-000101', '0000320193-19-000100', '0000320193-19-000099', '0000320193-19-000093', '0001193125-19-242975', '0001193125-19-238922', '0001193125-19-237993', '0001193125-19-237090', '0000320193-19-000090', '0000320193-19-000088', '0000320193-19-000086', '0000320193-19-000082', '0000320193-19-000081', '0000320193-19-000080', '0000320193-19-000076', '0000320193-19-000073', '0000320193-19-000070', '0000320193-19-000069', '0000320193-19-000066', '0000320193-19-000063', '0000320193-19-000060', '0000320193-19-000059', '0000320193-19-000058', '0000320193-19-000054', '0000320193-19-000052', '0000320193-19-000051', '0001354457-19-000130', '0001193125-19-074874', '0001193125-19-074868', '0000320193-19-000046', '0000320193-19-000045', '0000320193-19-000044', '0000320193-19-000043', '0000320193-19-000042', '0000320193-19-000041', '0000320193-19-000040', '0000320193-19-000032', '0001193125-19-041571', '0001193125-19-041014', '0000932471-19-004418', '0000320193-19-000030', '0000320193-19-000029', '0000320193-19-000026', '0000320193-19-000024', '0000320193-19-000023', '0000320193-19-000022', '0000320193-19-000021', '0000320193-19-000020', '0000320193-19-000019', '0000320193-19-000018', '0001214659-19-000797', '0000215457-19-003343', '0000320193-19-000010', '0000320193-19-000007', '0000320193-19-000004', '0001193125-19-004678', '0001193125-19-004664', '0000320193-19-000002', '0000320193-18-000149', '0000320193-18-000147', '0001193125-18-317844', '0000320193-18-000145', '0000320193-18-000142', '0000320193-18-000139', '0000320193-18-000137', '0000320193-18-000136', '0000320193-18-000135', '0000320193-18-000131', '0000320193-18-000130', '0000320193-18-000129', '0000320193-18-000125', '0000320193-18-000124', '0000320193-18-000123', '0000320193-18-000122', '0000320193-18-000121', '0000320193-18-000115', '0001193125-18-256354', '0000320193-18-000113', '0000320193-18-000112', '0000320193-18-000109', '0000320193-18-000107', '0000320193-18-000106', '0000320193-18-000103', '0000320193-18-000100', '0000320193-18-000098', '0000320193-18-000095', '0000320193-18-000092', '0000320193-18-000090', '0000320193-18-000088', '0000320193-18-000086', '0000320193-18-000084', '0000320193-18-000082', '0000320193-18-000080', '0000320193-18-000078', '0000320193-18-000076', '0000320193-18-000074', '0001193125-18-154948', '0000320193-18-000072', '0001193125-18-154515', '0000320193-18-000070', '0000320193-18-000067', '0000320193-18-000064', '0000320193-18-000063', '0000320193-18-000060', '0000320193-18-000058', '0000320193-18-000057', '0000320193-18-000054', '0000320193-18-000053', '0000320193-18-000052', '0000320193-18-000051', '0000320193-18-000050', '0000320193-18-000049', '0000320193-18-000048', '0001193125-18-073716', '0000320193-18-000040', '0000320193-18-000037', '0000320193-18-000036', '0000320193-18-000035', '0000320193-18-000034', '0000320193-18-000033', '0000320193-18-000032', '0000320193-18-000031', '0001193125-18-045761', '0000932471-18-004625', '0000320193-18-000023', '0000320193-18-000021', '0000320193-18-000020', '0000320193-18-000019', '0000320193-18-000018', '0000320193-18-000017', '0000320193-18-000016', '0000320193-18-000015', '0000320193-18-000007', '0000320193-18-000005', '0000215457-18-003762', '0000320193-18-000002', '0001193125-17-380132', '0001193125-17-380130', '0000320193-17-000087', '0000320193-17-000085', '0000320193-17-000083', '0000320193-17-000081', '0000320193-17-000079', '0000320193-17-000078', '0000320193-17-000077', '0001193125-17-341015', '0001193125-17-335805', '0001193125-17-334724', '0001193125-17-333582', '0000320193-17-000070', '0000320193-17-000067', '0000320193-17-000063', '0000320193-17-000062', '0000320193-17-000061', '0000320193-17-000060', '0000320193-17-000059', '0000320193-17-000058', '0000320193-17-000057', '0000320193-17-000056', '0000320193-17-000055', '0001193125-17-308859', '0000320193-17-000045', '0000320193-17-000043', '0000320193-17-000042', '0000320193-17-000039', '0000320193-17-000038', '0000320193-17-000037', '0000320193-17-000036', '0000320193-17-000035', '0000320193-17-000034', '0000320193-17-000033', '0000320193-17-000032', '0001193125-17-282809', '0001193125-17-277897', '0001193125-17-276961', '0001193125-17-276117', '0000320193-17-000023', '0000320193-17-000021', '0000320193-17-000018', '0001193125-17-262261', '0000320193-17-000017', '0001193125-17-258933', '0001193125-17-258729', '0001193125-17-258040', '0000320193-17-000015', '0000320193-17-000014', '0000320193-17-000013', '0000320193-17-000009', '0000320193-17-000006', '0000320193-17-000003', '0001193125-17-208226', '0001628280-17-006558', '0001193125-17-203548', '0001193125-17-202772', '0001193125-17-201958', '0001628280-17-006357', '0001628280-17-006261', '0001628280-17-006119', '0001628280-17-006040', '0001628280-17-005932', '9999999997-17-006550', '0001628280-17-005877', '0001628280-17-005876', '0001193125-17-181871', '0001193125-17-181867', '0001628280-17-005698', '0001193125-17-175330', '0001193125-17-173678', '0001193125-17-172693', '0001628280-17-005434', '0001628280-17-005433', '0001193125-17-167400', '0001628280-17-005184', '0001628280-17-005183', '0001193125-17-160948', '0001193125-17-159397', '0001193125-17-159324', '0001193125-17-157385', '0001628280-17-004826', '0001628280-17-004790', '0001628280-17-004663', '0001628280-17-004167', '0001628280-17-003836', '0001628280-17-003835', '0001628280-17-003834', '0001628280-17-003444', '0001628280-17-003442', '0001628280-17-003348', '0001628280-17-003347', '0001628280-17-003346', '0001628280-17-003345', '0001628280-17-003344', '0001628280-17-003343', '0001628280-17-003342', '0001628280-17-003341', '0001628280-17-002692', '0001628280-17-002321', '0001193125-17-069853', '0001628280-17-002133', '0001628280-17-002132', '0001628280-17-002131', '0001628280-17-002130', '0001628280-17-002129', '0001628280-17-002128', '0001628280-17-002127', '0001193125-17-064019', '0001628280-17-001737', '0001628280-17-001593', '0001628280-17-001484', '0001628280-17-001483', '0001193125-17-044564', '0001193125-17-042083', '0001193125-17-041233', '0001193125-17-036283', '0000932471-17-000777', '0001628280-17-000963', '0001628280-17-000897', '0001628280-17-000896', '0001628280-17-000895', '0001628280-17-000894', '0001628280-17-000893', '0001628280-17-000892', '0001628280-17-000891', '0001628280-17-000890', '0001628280-17-000889', '0001628280-17-000888', '0001193125-17-030832', '0001193125-17-029548', '0001193125-17-028315', '0001628280-17-000744', '0001628280-17-000717', '0001628280-17-000663', '0001214659-17-000547', '0001628280-17-000550', '0001628280-17-000379', '0001628280-17-000312', '0001628280-17-000311', '0000215457-17-001275', '0001628280-17-000187', '0001193125-17-003764', '0001193125-17-003753', '0001628280-16-022242', '0001628280-16-022104', '0001628280-16-022047', '0001628280-16-022020', '9999999997-17-000002', '0001628280-16-021649', '0001628280-16-021144', '0001628280-16-020880', '0001628280-16-020879', '0001628280-16-020489', '0001628280-16-020488', '9999999997-17-000809', '9999999997-16-026607', '0001628280-16-020309', '0001628280-16-020258', '0001628280-16-020124', '0001628280-16-020123', '0001628280-16-020122', '0001628280-16-020121', '0001628280-16-020120', '0001628280-16-020119', '0001628280-16-020118', '0001628280-16-020117', '0001628280-16-020116', '0001628280-16-020115', '0001628280-16-019941', '0001628280-16-019940', '0001628280-16-019939', '0001628280-16-019938', '0001628280-16-019937', '0001628280-16-019936', '0001628280-16-019935', '0001628280-16-019757', '0001628280-16-019756', '0001628280-16-019444', '0001628280-16-019324', '0001628280-16-019323', '0001628280-16-019269', '0001628280-16-019247', '0001628280-16-019246', '0001628280-16-019152', '0001628280-16-019151', '0001628280-16-019150', '0001628280-16-019109', '0001628280-16-019099', '0001628280-16-018921', '0001628280-16-018832', '0001628280-16-018636', '0001193125-16-672044', '0001193125-16-664603', '0001193125-16-662761', '0001193125-16-661201', '0001628280-16-017809', '0001628280-16-017762', '0001628280-16-017677', '0001193125-16-628957', '0001209191-16-128301', '0001193125-16-616649', '0001193125-16-615362', '0001193125-16-614374', '0001209191-16-125278', '0001209191-16-124774', '0001209191-16-124773', '0001209191-16-124771', '0001209191-16-124457', '0001209191-16-124453', '0001209191-16-123335', '0001209191-16-117168', '0001193125-16-564177', '0001193125-16-559625', '0001193125-16-556520', '0001209191-16-114938', '0001209191-16-114936', '0001209191-16-114935', '0001209191-16-113272', '0001209191-16-113271', '0001209191-16-113269', '0001209191-16-113268', '0001209191-16-113266', '0001209191-16-113265', '0001209191-16-111818', '0001193125-16-523320', '0001193125-16-516891', '0001209191-16-110273', '0001209191-16-110272', '0001209191-16-110271', '0001193125-16-510499', '0001193125-16-509001', '0001209191-16-109249', '0001193125-16-507590', '0001209191-16-107130', '0001209191-16-104163', '0001209191-16-104160', '0001209191-16-104159', '0001209191-16-104158', '0001209191-16-104157', '0001209191-16-104155', '0001209191-16-104154', '0001193125-16-488223', '0001193125-16-473562', '0001209191-16-099481', '0001193125-16-467194', '0001193125-16-466166', '0001193125-16-463982', '0000932471-16-011528', '0001209191-16-095503', '0001209191-16-095501', '0001209191-16-095500', '0001209191-16-095498', '0001209191-16-095495', '0001209191-16-095494', '0001209191-16-095491', '0001193125-16-439878', '0001193125-16-438421', '0000215457-16-002043', '0001214659-16-008862', '0001193125-16-422534', '0001193125-16-422528', '0001209191-15-087193', '0001193125-15-410853', '0001193125-15-406279', '9999999997-15-015765', '9999999997-15-016011', '9999999997-15-014868', '9999999997-15-014867', '0001209191-15-079403', '0001209191-15-078971', '0001209191-15-078197', '000

In [52]:
accessionNumber = [''.join(x.split('-')) for x in data["filings"]["recent"]["accessionNumber"]]

In [47]:
def get_accessionNumber(data):
    num = data.split('-')
    num = num[0]+num[1]
    return num
accessionNumber = get_accessionNumber(data["filings"]["recent"]["accessionNumber"])

AttributeError: 'dict' object has no attribute 'split'

In [53]:
data["filings"]["recent"]["primaryDocument"]

['ny20033611x3_8k.htm',
 'ny20033611x2_8k.htm',
 'xslF345X05/wk-form4_1724106610.xml',
 'xslF345X05/wk-form4_1723590126.xml',
 'xslF345X05/wk-form4_1723069808.xml',
 'xsl144X01/primary_doc.xml',
 'aapl-20240629.htm',
 'aapl-20240801.htm',
 'xslF345X05/wk-form4_1717453877.xml',
 'xsl144X01/primary_doc.xml',
 'xslF345X05/wk-form4_1715985021.xml',
 'filename1.pdf',
 'xslF345X05/wk-form4_1715725806.xml',
 'ef20028273_8k.htm',
 'aapl-20240330.htm',
 'aapl-20240502.htm',
 'filename1.htm',
 'xslF345X05/wk-form4_1713393040.xml',
 'xslF345X05/wk-form4_1713220262.xml',
 'xslF345X05/wk-form4_1713220215.xml',
 'xsl144X01/primary_doc.xml',
 'xsl144X01/primary_doc.xml',
 'filename1.htm',
 'xslF345X05/wk-form4_1712183631.xml',
 'xslF345X05/wk-form4_1712183580.xml',
 'xslF345X05/wk-form4_1712183535.xml',
 'xslF345X05/wk-form4_1712183493.xml',
 'xslF345X05/wk-form4_1712183434.xml',
 'xsl144X01/primary_doc.xml',
 'xsl144X01/primary_doc.xml',
 'xsl144X01/primary_doc.xml',
 'filename1.pdf',
 'ef20024616_sd.htm',
 'filename1.htm',
 'filename1.pdf',
 'xslF345X05/wk-form4_1709336196.xml',
 'xslF345X05/wk-form4_1709336160.xml',
 'xslF345X05/wk-form4_1709336113.xml',
 'xslF345X05/wk-form4_1709336072.xml',
 'xslF345X05/wk-form4_1709336002.xml',
 'xslF345X05/wk-form4_1709335956.xml',
 'xslF345X05/wk-form4_1709335906.xml',
 'xslF345X02/wk-form3_1709335848.xml',
 'xsl144X01/primary_doc.xml',
 'ny20022580x1_8k.htm',
 'd751537dsc13ga.htm',
 'tv0017-appleinc.htm',
 'us0378331005_021224.txt',
 'nlpc_px14a6g.htm',
 'xslF345X05/wk-form4_1707176223.xml',
 'xslF345X05/wk-form4_1707176183.xml',
 'xslF345X05/wk-form4_1707176141.xml',
 'xslF345X05/wk-form4_1707176086.xml',
 'xslF345X05/wk-form4_1707176011.xml',
 'xslF345X05/wk-form4_1707175959.xml',
 'xslF345X05/wk-form4_1707175909.xml',
 'xslF345X05/wk-form4_1707175857.xml',
 'bowy_px14a6g.htm',
 'bowy_px14a6g.htm',
 'aapl-20231230.htm',
 'aapl-20240201.htm',
 'bowy_px14a6g.htm',
 'bowy_px14a6g.htm',
 'bowy_px14a6g.htm',
 'bowy_px14a6g.htm',
 'j119245px14a6g.htm',
 'xslF25X02/primary_doc.xml',
 'laapl2024_defa14a.htm',
 'laapl2024_def14a.htm',
 'xslF345X05/wk-form4_1701473530.xml',
 'xslF345X05/wk-form4_1700523067.xml',
 'xslF345X05/wk-form4_1700004649.xml',
 'aapl-20230930.htm',
 'aapl-20231102.htm',
 'xslF345X05/wk-form4_1697581839.xml',
 'xslF345X05/wk-form4_1696977071.xml',
 'xslF345X05/wk-form4_1696977012.xml',
 'xsl144X01/primary_doc.xml',
 'xsl144X01/primary_doc.xml',
 'xsl144X01/primary_doc.xml',
 'xslF345X05/wk-form4_1696381746.xml',
 'xslF345X05/wk-form4_1696381688.xml',
 'xslF345X05/wk-form4_1696381604.xml',
 'xslF345X05/wk-form4_1696381514.xml',
 'xslF345X05/wk-form4_1696381457.xml',
 'xslF345X05/wk-form4_1696381345.xml',
 'xsl144X01/primary_doc.xml',
 'xsl144X01/primary_doc.xml',
 'xsl144X01/primary_doc.xml',
 'xslF345X05/wk-form4_1695162617.xml',
 'xslF345X05/wk-form4_1691533817.xml',
 'xsl144X01/primary_doc.xml',
 'aapl-20230701.htm',
 'aapl-20230803.htm',
 'xslF345X04/wf-form4_168444912415136.xml',
 'xslF345X04/wf-form4_168393061463065.xml',
 'xslF345X04/wf-form4_168375780902324.xml',
 'ny20007635x4_8k.htm',
 'ny20007635x3_424b2.htm',
 'ny20007635x2_fwp.htm',
 'ny20007635x1_424b2.htm',
 'aapl-20230401.htm',
 'aapl-20230504.htm',
 'xslF345X04/wf-form4_168185708431590.xml',
 'xslF345X04/wf-form4_168177065948283.xml',
 'xsl144X01/primary_doc.xml',
 'xslF345X04/wf-form4_168116581286812.xml',
 'xsl144X01/primary_doc.xml',
 'xslF345X04/wf-form4_168064766485466.xml',
 'xslF345X04/wf-form4_168064761527635.xml',
 'xslF345X04/wf-form4_168064754806371.xml',
 'xslF345X04/wf-form4_168064750462974.xml',
 'xslF345X04/wf-form4_168064745080973.xml',
 'xslF345X04/wf-form4_167969705479427.xml',
 'brhc10048434_sd.htm',
 'xslF345X03/wf-form4_167883332720098.xml',
 'xslF345X03/wf-form4_167883328933055.xml',
 'xslF345X03/wf-form4_167883325244111.xml',
 'xslF345X03/wf-form4_167883321069337.xml',
 'xslF345X03/wf-form4_167883316975236.xml',
 'xslF345X03/wf-form4_167883310220723.xml',
 'xslF345X03/wf-form4_167883306952487.xml',
 'xslF345X03/wf-form4_167883304133328.xml',
 'brhc10049413_8k.htm',
 'nlpc_px14a6g.htm',
 'nlpc_px14a6g.htm',
 'f214237px14a6g.htm',
 'nlpc_px14a6g.htm',
 'd382361dsc13ga.htm',
 'tv0017-appleinc.htm',
 'us0378331005_020723.txt',
 'xslF345X03/wf-form4_167546747536649.xml',
 'xslF345X03/wf-form4_167546742335512.xml',
 'xslF345X03/wf-form4_167546736542524.xml',
 'xslF345X03/wf-form4_167546729886985.xml',
 'xslF345X03/wf-form4_167546724839309.xml',
 'xslF345X03/wf-form4_167546717269434.xml',
 'xslF345X03/wf-form4_167546711444862.xml',
 'xslF345X03/wf-form4_167546705890329.xml',
 'brhc10047294_defa14a.htm',
 'aapl-20221231.htm',
 'aapl-20230202.htm',
 'd126231px14a6g.htm',
 'f120232px14a6g.htm',
 'laap2023_def14a.htm',
 'laap2023_def14a.htm',
 'xslF345X03/wf-form4_166924620985339.xml',
 'xslF25X02/primary_doc.xml',
 'd400465d8k.htm',
 'xslF345X03/wf-form4_166734181374173.xml',
 'aapl-20220924.htm',
 'aapl-20221027.htm',
 'xslF345X03/wf-form4_166613234346671.xml',
 'xslF345X03/wf-form4_166613226881196.xml',
 'xslF345X03/wf-form4_166493494107053.xml',
 'xslF345X03/wf-form4_166493432440801.xml',
 'xslF345X03/wf-form4_166493485929155.xml',
 'xslF345X03/wf-form4_166493500034922.xml',
 'xslF345X03/wf-form4_166432987613616.xml',
 'xslF345X03/wf-form4_166432981128707.xml',
 'xslF345X03/wf-form4_166432973592639.xml',
 'xslF345X03/wf-form4_166432966938808.xml',
 'xslF345X03/wf-form4_166432958917508.xml',
 'xslF345X03/wf-form4_166432952647630.xml',
 'xslF345X03/wf-form4a_166120817922787.xml',
 'xslF345X03/wf-form4_166094821148314.xml',
 'd366128d8k.htm',
 'xslF345X03/wf-form4_166008422355199.xml',
 'd297151d8k.htm',
 'xslF345X03/wf-form4_165973862846098.xml',
 'd358144d424b2.htm',
 'd297161dfwp.htm',
 'd358144d424b2.htm',
 'aapl-20220625.htm',
 'aapl-20220728.htm',
 'xslF345X03/wf-form4_165248105838188.xml',
 'xslF345X03/wf-form4_165187623819106.xml',
 'd332661ds8.htm',
 'd279200ds8pos.htm',
 'd279200ds8pos.htm',
 'aapl-20220326.htm',
 'aapl-20220428.htm',
 'xslF345X03/wf-form4_165040749395911.xml',
 'xslF345X03/wf-form4_165040742689204.xml',
 'xslF345X03/wf-form4_164919799612317.xml',
 'xslF345X03/wf-form4_164919793500496.xml',
 'xslF345X03/wf-form4_164919788707106.xml',
 'xslF345X03/wf-form4_164919783103450.xml',
 'xslF345X03/wf-form4_164678264350913.xml',
 'xslF345X03/wf-form4_164678259356672.xml',
 'xslF345X03/wf-form4_164678253465583.xml',
 'xslF345X03/wf-form4_164678248157775.xml',
 'xslF345X03/wf-form4_164678242279764.xml',
 'xslF345X03/wf-form4_164678236531567.xml',
 'xslF345X03/wf-form4_164678229722183.xml',
 'xslF345X03/wf-form4_164678223741209.xml',
 'd294699d8k.htm',
 'd288870dsd.htm',
 'tv0011-appleinc.htm',
 'f28220px14a6g.htm',
 'xslF345X03/wf-form4_164427662367600.xml',
 'xslF345X03/wf-form4_164393152667942.xml',
 'xslF345X03/wf-form4_164393146754706.xml',
 'xslF345X03/wf-form4_164393139518938.xml',
 'xslF345X03/wf-form4_164393133439643.xml',
 'xslF345X03/wf-form4_164393124898522.xml',
 'xslF345X03/wf-form4_164393117233036.xml',
 'xslF345X03/wf-form4_164393109986560.xml',
 'xslF345X03/wf-form4_164393104282208.xml',
 'g131227px14a6g.htm',
 'g131228px14a6g.htm',
 'us0378331005_012822.txt',
 'e126223px14a6g.htm',
 'aapl-20211225.htm',
 'aapl-20220127.htm',
 'aapldearshareholder.htm',
 'd399129ddefa14a.htm',
 'd222670ddef14a.htm',
 'xslF345X03/wf-form4_163710541081314.xml',
 'xslF345X03/wf-form4_163675992058856.xml',
 'xslF345X02/wf-form3_163675983081322.xml',
 'd259993d8k.htm',
 'xslF345X03/wf-form4_163597867263388.xml',
 'd192862ds3asr.htm',
 'd246143dirannotice.htm',
 'aapl-20210925.htm',
 'aapl-20211028.htm',
 'xslF345X03/wf-form4_163485542776887.xml',
 'xslF345X03/wf-form4_163468269006289.xml',
 'xslF345X03/wf-form4_163468261390808.xml',
 'xslF345X03/wf-form4_163347386959085.xml',
 'xslF345X03/wf-form4_163347379860494.xml',
 'xslF345X03/wf-form4_163347373433784.xml',
 'xslF345X03/wf-form4_163347311336788.xml',
 'xslF345X03/wf-form4_163286851816033.xml',
 'xslF345X03/wf-form4_163286847648313.xml',
 'xslF345X03/wf-form4_163286842980488.xml',
 'xslF345X03/wf-form4_163286838690995.xml',
 'xslF345X03/wf-form4_163286834378268.xml',
 'xslF345X03/wf-form4_163286823606839.xml',
 'xslF345X03/wf-form4_163001701613155.xml',
 'xslF345X03/wf-form4_162984422696515.xml',
 'xslF345X03/wf-form4_162854822510730.xml',
 'd199884d8k.htm',
 'xslF345X03/wf-form4_162811622543495.xml',
 'd175814d424b2.htm',
 'd202672dfwp.htm',
 'd175814d424b2.htm',
 'd198818dirannotice.htm',
 'aapl-20210626.htm',
 'aapl-20210727.htm',
 'xslF345X03/wf-form4_162025388592461.xml',
 'xslF345X03/wf-form4_162025381465785.xml',
 'aapl-20210327.htm',
 'aapl-20210428.htm',
 'xslF345X03/wf-form4_161887148361718.xml',
 'xslF345X03/wf-form4_161887141797206.xml',
 'xslF345X03/wf-form4_161766207883637.xml',
 'xslF345X03/wf-form4_161766194119040.xml',
 'xslF345X03/wf-form4_161766181877540.xml',
 'xslF345X03/wf-form4_161429622893015.xml',
 'xslF345X03/wf-form4_161429614827041.xml',
 'xslF345X03/wf-form4_161429609463628.xml',
 'xslF345X03/wf-form4_161429604194177.xml',
 'xslF345X03/wf-form4_161429598243346.xml',
 'xslF345X03/wf-form4_161429591861303.xml',
 'xslF345X03/wf-form4_161429585074371.xml',
 'd101693d8k.htm',
 'r217211px14a6g.htm',
 'd107461dsc13ga.htm',
 'd119389dsd.htm',
 'tv0010-appleinc.htm',
 'd70217d8k.htm',
 'us0378331005_020421.txt',
 'xslF345X03/wf-form4_161239555356050.xml',
 'xslF345X03/wf-form4_161239548384646.xml',
 'xslF345X03/wf-form4_161239542324805.xml',
 'xslF345X03/wf-form4_161239535474705.xml',
 'xslF345X03/wf-form4_161239528138893.xml',
 'xslF345X03/wf-form4_161239515778792.xml',
 'xslF345X03/wf-form4_161239509434831.xml',
 'xslF345X03/wf-form4_161239502964926.xml',
 'd66851d424b2.htm',
 'd70069dfwp.htm',
 'd66851d424b2.htm',
 'aapl-20201226.htm',
 'aapl-20210127.htm',
 'xslF345X03/wf-form4_160988957683472.xml',
 'xslF345X02/wf-form3_160988944878908.xml',
 'd767776ddefa14a.htm',
 'd767770ddef14a.htm',
 'd29637d8k.htm',
 'xslF345X03/wf-form4_160565582610158.xml',
 'xslF345X03/wf-form4_160461904119340.xml',
 'aapl-20200926.htm',
 'aapl-20201029.htm',
 'xslF345X03/wf-form4_160314673986899.xml',
 'xslF345X03/wf-form4_160314661733333.xml',
 'xslF345X03/wf-form4_160262821333467.xml',
 'xslF345X03/wf-form4_160193720275669.xml',
 'xslF345X03/wf-form4_160193715587800.xml',
 'xslF345X03/wf-form4_160193701297920.xml',
 'xslF345X03/wf-form4_160141899239637.xml',
 'xslF345X03/wf-form4_160141893471775.xml',
 'xslF345X03/wf-form4_160141889148665.xml',
 'xslF345X03/wf-form4_160141884313005.xml',
 'xslF345X03/wf-form4_160141879027128.xml',
 'xslF345X03/wf-form4_160141863355452.xml',
 'xslF345X03/wf-form4_159839550969947.xml',
 'xslF345X03/wf-form4_159830825188983.xml',
 'd937363d8k.htm',
 'd23503d424b2.htm',
 'd82525dfwp.htm',
 'd23503d424b2.htm',
 'd49399d8k.htm',
 'aapl-20200627.htm',
 'aapl-20200730.htm',
 'xslF345X03/wf-form4_158932261319105.xml',
 'd926511d8k.htm',
 'd926392d424b2.htm',
 'd926508dfwp.htm',
 'd926392d424b2.htm',
 'a10-qq220203282020.htm',
 'xslF345X03/wf-form4_158829658358801.xml',
 'a8-kq220203282020.htm',
 'xslF345X03/wf-form4_158716268511263.xml',
 'xslF345X03/wf-form4_158716262832690.xml',
 'xslF345X03/wf-form4_158647142758084.xml',
 'xslF345X03/wf-form4_158595308536827.xml',
 'xslF345X03/wf-form4_158595302992961.xml',
 'xslF345X03/wf-form4_158293300685250.xml',
 'xslF345X03/wf-form4_158293293482087.xml',
 'xslF345X03/wf-form4_158293286599770.xml',
 'xslF345X03/wf-form4_158293278709070.xml',
 'xslF345X03/wf-form4_158293272634137.xml',
 'xslF345X03/wf-form4_158293266204383.xml',
 'd865740d8k.htm',
 'd845033d8k.htm',
 'd852265dsc13ga.htm',
 'tv01779-appleinc.htm',
 'us0378331005_020720.txt',
 'd877299dsd.htm',
 'xslF345X03/wf-form4_158085938309797.xml',
 'xslF345X03/wf-form4_158085933339951.xml',
 'xslF345X03/wf-form4_158085927075591.xml',
 'xslF345X03/wf-form4_158085920919420.xml',
 'xslF345X03/wf-form4_158085915125497.xml',
 'xslF345X03/wf-form4_158085910047342.xml',
 'xslF345X03/wf-form4_158034061831540.xml',
 'a10-qq1202012282019.htm',
 'a8-kq1202012282019.htm',
 'j127200px14a6g.htm',
 'aapl-px14a6g_022620.htm',
 'd799146ddefa14a.htm',
 'd799303ddef14a.htm',
 'xslF345X03/wf-form4_157800786035380.xml',
 '8A_Cert_AAPL.pdf',
 'd827578d8a12b.htm',
 'd828969d8k.htm',
 'xslF345X03/wf-form4_157377424820890.xml',
 'd804226d424b2.htm',
 'xslF345X03/wf-form4_157316940649990.xml',
 'd826022dfwp.htm',
 'd804226d424b2.htm',
 'd800564ds8pos.htm',
 'a10-k20199282019.htm',
 'a8-kq420199282019.htm',
 'xslF345X03/wf-form4_157135154697018.xml',
 'xslF345X03/wf-form4_157135144806488.xml',
 'xslF345X03/wf-form4_157066032478147.xml',
 'xslF345X03/wf-form4_157014197957378.xml',
 'xslF345X03/wf-form4_157014186524822.xml',
 'xslF345X03/wf-form4_156996927774723.xml',
 'xslF345X03/wf-form4_156996921603511.xml',
 'xslF345X03/wf-form4_156996915065922.xml',
 'xslF345X03/wf-form4_156996908478756.xml',
 'xslF345X03/wf-form4_156996902282904.xml',
 'a8-kseptember201991019.htm',
 'd777124d8k.htm',
 'd751814d424b2.htm',
 'd777130dfwp.htm',
 'd751814d424b2.htm',
 'xslF345X03/wf-form4_156694501621463.xml',
 'xslF345X03/wf-form4_156685147551694.xml',
 'xslF345X03/wf-form4_156582182214854.xml',
 'xslF345X03/wf-form4_156504439014885.xml',
 'xslF345X03/wf-form4_156504433855286.xml',
 'xslF345X03/wf-form4_156504427145036.xml',
 'a10-qq320196292019.htm',
 'a8-kq320196292019.htm',
 'xslF345X03/wf-form4_155726823464315.xml',
 'xslF345X03/wf-form4_155718184308434.xml',
 'a10-qq220193302019.htm',
 'a8-kq220193302019.htm',
 'xslF345X03/wf-form4_155554044049297.xml',
 'xslF345X03/wf-form4_155554036612827.xml',
 'xslF345X02/wf-form3a_155554028715520.xml',
 'xslF345X03/wf-form4_155484903395532.xml',
 'xslF345X03/wf-form4_155433069460529.xml',
 'xslF345X03/wf-form4_155433063141322.xml',
 'AAPL_Cert.pdf',
 'd719398d25.htm',
 'd720211d8a12b.htm',
 'xslF345X03/wf-form4_155182895326790.xml',
 'xslF345X03/wf-form4_155182889283168.xml',
 'xslF345X03/wf-form4_155182883124053.xml',
 'xslF345X03/wf-form4_155182876082716.xml',
 'xslF345X03/wf-form4_155182869211407.xml',
 'xslF345X03/wf-form4_155182861814144.xml',
 'xslF345X03/wf-form4_155182854534604.xml',
 'copyofreference8-kform8xkq.htm',
 'd694085dsd.htm',
 'd667611dsc13g.htm',
 'appleinc.htm',
 'xslF345X03/wf-form4_154958296589351.xml',
 'xslF345X02/wf-form3_154958223758270.xml',
 'a8-kfebruary2019252019.htm',
 'xslF345X03/wf-form4_154941004809567.xml',
 'xslF345X03/wf-form4_154940998460508.xml',
 'xslF345X03/wf-form4_154940992221908.xml',
 'xslF345X03/wf-form4_154940984777970.xml',
 'xslF345X03/wf-form4_154940978487594.xml',
 'xslF345X03/wf-form4_154940971963917.xml',
 'xslF345X03/wf-form4_154940965388838.xml',
 'j24190px14a6g.htm',
 'us0378331005_020419.txt',
 'a10-qq1201912292018.htm',
 'a8-kq1201912292018.htm',
 'xslF345X03/wf-form4_154871824787707.xml',
 'd668059ddefa14a.htm',
 'd667873ddef14a.htm',
 'a8-kjanuary2019122019.htm',
 'xslF345X03/wf-form4_154284308216532.xml',
 'xslF345X03/wf-form4_154232465480280.xml',
 'd644900ds3asr.htm',
 'a10-k20189292018.htm',
 'a8-kq420189292018.htm',
 'xslF345X03/wf-form4_153981541459967.xml',
 'xslF345X03/wf-form4_153877878310747.xml',
 'xslF345X03/wf-form4_153877872133212.xml',
 'xslF345X03/wf-form4_153877866095942.xml',
 'xslF345X03/wf-form4_153860603163051.xml',
 'xslF345X03/wf-form4_153860597104703.xml',
 'xslF345X03/wf-form4_153860589217680.xml',
 'xslF345X03/wf-form4_153851977931242.xml',
 'xslF345X03/wf-form4_153851972725526.xml',
 'xslF345X03/wf-form4_153851966439459.xml',
 'xslF345X03/wf-form4_153851960893694.xml',
 'xslF345X03/wf-form4_153851955377044.xml',
 'xslF345X03/wf-form4_153549547286956.xml',
 'd609898ds8.htm',
 'xslF345X03/wf-form4_153489248141557.xml',
 'xslF345X03/wf-form4_153489235873857.xml',
 'xslF345X03/wf-form4_153454502801733.xml',
 'xslF345X03/wf-form4_153394039211365.xml',
 'xslF345X03/wf-form4_153394028523209.xml',
 'xslF345X03/wf-form4_153359461891019.xml',
 'a10-qq320186302018.htm',
 'a8-kq320186302018.htm',
 'xslF345X03/wf-form4_153134826427557.xml',
 'xslF345X03/wf-form4_152936101490685.xml',
 'xslF345X03/wf-form4_152884262050898.xml',
 'xslF345X03/wf-form4_152815141411532.xml',
 'xslF345X03/wf-form4_152780585957689.xml',
 'xslF345X03/wf-form4_152728745985789.xml',
 'xslF345X03/wf-form4_152694183324049.xml',
 'xslF345X03/wf-form4_152668264478876.xml',
 'xslF345X03/wf-form4_152642343017017.xml',
 'xslF345X03/wf-form4_152607794990188.xml',
 'xslF345X03/wf-form4_152599148061399.xml',
 'd563832d8ka.htm',
 'xslF345X03/wf-form4_152573222606599.xml',
 'd563832d8k.htm',
 'a10-qq220183312018.htm',
 'a8-kq220183312018.htm',
 'xslF345X03/wf-form4_152400428847158.xml',
 'xslF345X03/wf-form4_152400423176100.xml',
 'xslF345X03/wf-form4_152391784210514.xml',
 'xslF345X03/wf-form4_152305384529017.xml',
 'xslF345X03/wf-form4_152296745064089.xml',
 'xslF345X03/wf-form4_152279495069184.xml',
 'xslF345X03/wf-form4_152279488511967.xml',
 'xslF345X03/wf-form4_152279483540589.xml',
 'xslF345X03/wf-form4_152279479066592.xml',
 'xslF345X03/wf-form4_152279471770222.xml',
 'xslF345X03/wf-form4_152279465769401.xml',
 'xslF345X03/wf-form4_152279460818145.xml',
 'd538673dsd.htm',
 'xslF345X03/wf-form4_151916941098122.xml',
 'xslF345X03/wf-form4_151873776941650.xml',
 'xslF345X03/wf-form4_151873771953304.xml',
 'xslF345X03/wf-form4_151873766872367.xml',
 'xslF345X03/wf-form4_151873761103884.xml',
 'xslF345X03/wf-form4_151873755044531.xml',
 'xslF345X03/wf-form4_151873748320537.xml',
 'xslF345X03/wf-form4_151873742057861.xml',
 'd374908d8k.htm',
 'appleinc.htm',
 'xslF345X03/wf-form4_151813262859954.xml',
 'xslF345X03/wf-form4_151787379347066.xml',
 'xslF345X03/wf-form4_151787375000361.xml',
 'xslF345X03/wf-form4_151787368848629.xml',
 'xslF345X03/wf-form4_151787363289356.xml',
 'xslF345X03/wf-form4_151787355536092.xml',
 'xslF345X03/wf-form4_151787350514336.xml',
 'xslF345X03/wf-form4_151787343921146.xml',
 'a10-qq1201812302017.htm',
 'a8-kq1201812302017.htm',
 'us0378331005_012918.txt',
 'xslF345X03/wf-form4_151554062441822.xml',
 'd396272ddefa14a.htm',
 'd400278ddef14a.htm',
 'xslF345X03/wf-form4_151303504615549.xml',
 'xslF345X03/wf-form4_151243036024161.xml',
 'xslF345X03/wf-form4_151182543114594.xml',
 'xslF345X03/wf-form4_151087508159949.xml',
 'xslF345X03/wf-form4_151078880413808.xml',
 'xslF345X03/wf-form4_151078874247280.xml',
 'xslF345X02/wf-form3_151078866524134.xml',
 'd478060d8k.htm',
 'd475365d424b2.htm',
 'd480547dfwp.htm',
 'd475365d424b2.htm',
 'a10-k20179302017.htm',
 'a8-kq420179302017.htm',
 'xslF345X03/wf-form4_150828044948163.xml',
 'xslF345X03/wf-form4_150828038824181.xml',
 'xslF345X03/wf-form4_150828027600542.xml',
 'xslF345X03/wf-form4_150828022415662.xml',
 'xslF345X03/wf-form4_150828017246106.xml',
 'xslF345X03/wf-form4_150828010037766.xml',
 'xslF345X03/wf-form4_150828003638615.xml',
 'xslF345X03/wf-form4_150827998628260.xml',
 'xslF345X03/wf-form4_150827993959614.xml',
 'd386231d8k.htm',
 'xslF345X03/wf-form4_150767467144201.xml',
 'xslF345X03/wf-form4_150724283880617.xml',
 'xslF345X03/wf-form4_150724278525543.xml',
 'xslF345X03/wf-form4_150707026587310.xml',
 'xslF345X03/wf-form4_150707022096581.xml',
 'xslF345X03/wf-form4_150707017081508.xml',
 'xslF345X03/wf-form4_150707011795652.xml',
 'xslF345X03/wf-form4_150707006333873.xml',
 'xslF345X03/wf-form4_150707000038940.xml',
 'xslF345X03/wf-form4_150706994103772.xml',
 'xslF345X03/wf-form4_150706989617764.xml',
 'd434478d8k.htm',
 'd453793d424b2.htm',
 'd451794dfwp.htm',
 'd453793d424b2.htm',
 'xslF345X03/wf-form4_150413222111835.xml',
 'xslF345X03/wf-form4_150396481887759.xml',
 'xslF345X03/wf-form4_150309542055431.xml',
 'd593893d8k.htm',
 'xslF345X03/wf-form4_150300904326605.xml',
 'd433785d424b2.htm',
 'd612765dfwp.htm',
 'd433785d424b2.htm',
 'xslF345X03/wf-form4_150231792959896.xml',
 'xslF345X03/wf-form4_150231787803625.xml',
 'xslF345X03/wf-form4_150231783126553.xml',
 'a10-qq32017712017.htm',
 'a8-kq32017712017.htm',
 'xslF345X03/wf-form4_149972580917613.xml',
 'd413980d8k.htm',
 'xslF345X03/wf-form4_149765220991664.xml',
 'd412075d424b2.htm',
 'd413957dfwp.htm',

In [56]:
data["cik"]

'320193'

In [60]:
accessionNumber[0]

'000114036124038601'

In [78]:
import requests

url = "https://www.sec.gov/Archives/edgar/data/320193/000114036124038601/ny20033611x3_8k.htm"

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
    'Accept-Language': 'en-US,en;q=0.9',
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    print(response.text)
else:
    print(f"Error: {response.status_code}")

Error: 403

In [61]:
#for accession, primarydoc in zip(accessionNumber, data["filings"]["recent"]["primaryDocument"]):
cik = data["cik"]
acc_num = accessionNumber[0]
primary_doc = data["filings"]["recent"]["primaryDocument"][0]

custom_url = f"https://www.sec.gov/Archives/edgar/data/{cik}/{acc_num}/{primary_doc}"
print(custom_url)

https://www.sec.gov/Archives/edgar/data/320193/000114036124038601/ny20033611x3_8k.htm

In [62]:
load_json_data(custom_url)

Error fetching JSON data: 403 Client Error: Forbidden for url: https://www.sec.gov/Archives/edgar/data/320193/000114036124038601/ny20033611x3_8k.htm

In [12]:
data["filings"].keys()

dict_keys(['recent', 'files'])

In [38]:
data["filings"]["files"]

[{'name': 'CIK0000320193-submissions-001.json',
  'filingCount': 1075,
  'filingFrom': '1994-01-26',
  'filingTo': '2014-02-03'}]

In [ ]:
"https://www.sec.gov/Archives/edgar/data/{cik}/{accessionNumber}/{primaryDocument}"

In [35]:
l = ""
for k in data["filings"]["recent"]["accessionNumber"][0].split('-'):
    l = l+k
l

'000095017024087441'

In [35]:
data["filings"]["recent"]["form"]

['8-K',
 '8-K',
 '4',
 '4',
 '4',
 '144',
 '10-Q',
 '8-K',
 '4',
 '144',
 '4',
 'UPLOAD',
 '4',
 '8-K',
 '10-Q',
 '8-K',
 'CORRESP',
 '4',
 '4',
 '4',
 '144',
 '144',
 'CORRESP',
 '4',
 '4',
 '4',
 '4',
 '4',
 '144',
 '144',
 '144',
 'UPLOAD',
 'SD',
 'CORRESP',
 'UPLOAD',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '144',
 '8-K',
 'SC 13G/A',
 'SC 13G/A',
 'SC 13G/A',
 'PX14A6G',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'PX14A6G',
 'PX14A6G',
 '10-Q',
 '8-K',
 'PX14A6G',
 'PX14A6G',
 'PX14A6G',
 'PX14A6G',
 'PX14A6G',
 '25-NSE',
 'DEFA14A',
 'DEF 14A',
 '4',
 '4',
 '4',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '144',
 '144',
 '144',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '144',
 '144',
 '144',
 '4',
 '4',
 '144',
 '10-Q',
 '8-K',
 '4',
 '4',
 '4',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '10-Q',
 '8-K',
 '4',
 '4',
 '144',
 '4',
 '144',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'SD',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 'PX14A6G',
 'PX14A6G',
 'PX14A6G',
 'PX14A6G',
 'SC 13G/A',
 'SC 13G/A',
 'SC 13G/A',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'DEFA14A',
 '10-Q',
 '8-K',
 'PX14A6G',
 'PX14A6G',
 'DEFA14A',
 'DEF 14A',
 '4',
 '25-NSE',
 '8-K',
 '4',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4/A',
 '4',
 '8-K',
 '4',
 '8-K',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '10-Q',
 '8-K',
 '4',
 '4',
 'S-8',
 'S-8 POS',
 'S-8 POS',
 '10-Q',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 'SD',
 'SC 13G/A',
 'PX14A6G',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'PX14A6G',
 'PX14A6G',
 'SC 13G/A',
 'PX14A6G',
 '10-Q',
 '8-K',
 'PX14A6N',
 'DEFA14A',
 'DEF 14A',
 '4',
 '4',
 '3',
 '8-K',
 '4',
 'S-3ASR',
 'IRANNOTICE',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '4',
 '424B2',
 'FWP',
 '424B2',
 'IRANNOTICE',
 '10-Q',
 '8-K',
 '4',
 '4',
 '10-Q',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 'PX14A6G',
 'SC 13G/A',
 'SD',
 'SC 13G/A',
 '8-K',
 'SC 13G/A',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '10-Q',
 '8-K',
 '4',
 '3',
 'DEFA14A',
 'DEF 14A',
 '8-K',
 '4',
 '4',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '8-K',
 '10-Q',
 '8-K',
 '4',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '10-Q',
 '4',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '8-K',
 'SC 13G/A',
 'SC 13G/A',
 'SC 13G/A',
 'SD',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '10-Q',
 '8-K',
 'PX14A6G',
 'PX14A6G',
 'DEFA14A',
 'DEF 14A',
 '4',
 'CERT',
 '8-A12B',
 '8-K',
 '4',
 '424B2',
 '4',
 'FWP',
 '424B2',
 'S-8 POS',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '10-Q',
 '8-K',
 '4',
 '4',
 '10-Q',
 '8-K',
 '4',
 '4',
 '3/A',
 '4',
 '4',
 '4',
 'CERT',
 '25',
 '8-A12B',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 'SD',
 'SC 13G',
 'SC 13G/A',
 '4',
 '3',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'PX14A6G',
 'SC 13G/A',
 '10-Q',
 '8-K',
 '4',
 'DEFA14A',
 'DEF 14A',
 '8-K',
 '4',
 '4',
 'S-3ASR',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'S-8',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '10-Q',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K/A',
 '4',
 '8-K',
 '10-Q',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'SD',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 'SC 13G/A',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '10-Q',
 '8-K',
 'SC 13G/A',
 '4',
 'DEFA14A',
 'DEF 14A',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '4',
 '4',
 '8-K',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '4',
 '4',
 '10-Q',
 '8-K',
 '4',
 '8-K',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '4',
 '4',
 '4',
 '4',
 'CERTNYS',
 '4',
 '4',
 '8-A12B',
 '8-K',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '4',
 '8-K',
 '4',
 '4',
 '424B2',
 'SD',
 'FWP',
 '424B2',
 '4',
 '10-Q',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '8-K',
 'SC 13G/A',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '10-Q',
 '8-K',
 'PX14A6G',
 '4',
 '4',
 '4',
 '4',
 'SC 13G/A',
 '4',
 'DEFA14A',
 'DEF 14A',
 '4',
 '4',
 '8-K',
 '4',
 'NO ACT',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'NO ACT',
 'NO ACT',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '10-Q',
 '8-K',
 '4',
 '8-K',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'S-3ASR',
 '10-Q',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'SD',
 '8-K',
 '4',
 '4',
 '4',
 '424B2',
 'FWP',
 '4',
 '424B2',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '8-K',
 '4',
 '424B2',
 'FWP',
 '424B2',
 'SC 13G/A',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '10-Q',
 '8-K',
 'SC 13G/A',
 'PX14A6G',
 'DEFA14A',
 'DEF 14A',
 '3',
 '8-K',
 '8-K',
 'NO ACT',
 'NO ACT',
 'NO ACT',
 'NO ACT',
 '4',
 '4',
 '4',
 '4',
 '4',
 '10-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '3',
 '8-K',
 'CERTNYS',
 '4',
 '8-A12B',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '4',
 'UPLOAD',
 'CORRESP',
 '4',
 '4',
 '4',
 'CERTNYS',
 '8-A12B',
 '8-K',
 '4',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '10-Q',
 '4',
 '8-K',
 '4',
 '8-K',
 '424B2',
 'FWP',
 '4',
 '424B2',
 '4',
 '4',
 'UPLOAD',
 '8-K',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '4',
 'S-8',
 '10-Q',
 '4',
 '4',
 '8-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'CORRESP',
 '4',
 '4',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'UPLOAD',
 '4',
 '4',
 'SD',
 'SC 13G',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '424B2',
 'FWP',
 'SC 13G/A',
 '424B2',
 '3',
 '8-K',
 '10-Q',
 '4',
 '8-K',
 'DEFA14A',
 'DEF 14A',
 '4',
 'NO ACT',
 'NO ACT',
 '4',
 'NO ACT',
 'NO ACT',
 '4',
 '4',
 'CERTNYS',
 '8-A12B',
 '8-K',
 '4',
 '424B2',
 'FWP',
 '424B2',
 '4',
 '10-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '10-Q',
 '8-K',
 '4',
 '3',
 '8-K',
 '4',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 'SD',
 '8-K',
 '4',
 '3',
 '424B2',
 'FWP',
 '424B2',
 '4',
 'S-8',
 '4',
 '10-Q',
 '8-K',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '8-K',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 'PX14A6G',
 'PX14A6G',
 'PX14A6G',
 'PX14A6G',
 '4',
 '4',
 '4',
 '4',
 ...]

In [7]:
import pandas as pd

pd.DataFrame.from_dict(data, orient="index")

                                                                                   0
cik                                                                          1318605
entityType                                                                 operating
sic                                                                             3711
sicDescription                                 Motor Vehicles & Passenger Car Bodies
insiderTransactionForOwnerExists                                                   0
insiderTransactionForIssuerExists                                                  1
name                                                                     Tesla, Inc.
tickers                                                                       [TSLA]
exchanges                                                                   [Nasdaq]
ein                                                                        912197729
description
website
investorWebsite
category                                                     Large accelerated filer
fiscalYearEnd                                                                   1231
stateOfIncorporation                                                              DE
stateOfIncorporationDescription                                                   DE
addresses                          {'mailing': {'street1': '3500 DEER CREEK RD', ...
phone                                                                   650-681-5000
flags
formerNames                        [{'name': 'TESLA MOTORS INC', 'from': '2005-02...
filings                            {'recent': {'accessionNumber': ['0000950170-24...

# Ticker list

In [9]:
import requests

def download_file(url, filename):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Referer": "https://www.sec.gov/",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
    }
    
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Check if the request was successful

        # Write the content to a local file
        with open(filename, 'wb') as file:
            file.write(response.content)
        
        print(f"File downloaded successfully: {filename}")
    except requests.RequestException as e:
        print(f"Error downloading the file: {e}")

# URL of the file to download
url = "https://www.sec.gov/include/ticker.txt"
# Local filename where the file will be saved
filename = "ticker.txt"

# Download the file
download_file(url, filename)

File downloaded successfully: ticker.txt

In [37]:
import pandas as pd

def load_txt_and_transform_to_json(txt_filepath, json_filepath, delimiter=None, header='infer'):
    """
    Load a text file into a Pandas DataFrame, and transform it into a JSON file.
    
    Args:
        txt_filepath (str): Path to the text file.
        json_filepath (str): Path where the JSON file will be saved.
        delimiter (str, optional): Delimiter used in the text file. If None, pandas will infer the delimiter.
        header (int or 'infer', optional): Row to use as column names. Default is 'infer'.
        
    Returns:
        None: The function saves the DataFrame as a JSON file.
    """
    try:
        # Load the text file into a pandas DataFrame
        df = pd.read_csv(txt_filepath, delimiter=delimiter, header=header)
        
        # Convert the DataFrame to a JSON file
        df.to_json(json_filepath, orient='records', lines=True)
        
        print(f"File successfully transformed to JSON and saved at {json_filepath}")
    
    except Exception as e:
        print(f"An error occurred: {e}")

In [4]:
# Example usage:
txt_filepath = '../data/ticker.txt'  # Replace with the path to your .txt file
json_filepath = '../data/ticker.json'  # Replace with the path to save the .json file

# Load and transform the file
load_txt_and_transform_to_json(txt_filepath, json_filepath, delimiter=',')  # Replace the delimiter if necessary

NameError: name 'load_txt_and_transform_to_json' is not defined

In [3]:
import pandas as pd

txt_filepath = '../data/ticker.txt'  # Replace with the path to your .txt file

df = pd.read_csv(txt_filepath, sep=" ",  header=None, names=["cik"])

In [4]:
df_cik = pd.DataFrame([ci.split("\t")for ci in df["cik"].values], columns=["ticker","cik"])

In [5]:
df_cik

      ticker      cik
0       aapl   320193
1       msft   789019
2      brk-b  1067983
3        unh   731766
4        jnj   200406
...      ...      ...
12079  hcicu  1829455
12080  hcicw  1829455
12081  hawlm    46207
12082  hbanm    49196
12083  hbanp    49196

[12084 rows x 2 columns]

In [8]:
df_cik

      ticker      cik
0       aapl   320193
1       msft   789019
2      brk-b  1067983
3        unh   731766
4        jnj   200406
...      ...      ...
12079  hcicu  1829455
12080  hcicw  1829455
12081  hawlm    46207
12082  hbanm    49196
12083  hbanp    49196

[12084 rows x 2 columns]

In [9]:
k = {}

In [26]:
cache = '0' * 10
cache

'0000000000'

In [27]:
my_dict = {}
for key in df_cik["ticker"]:
    cik = df_cik[df_cik["ticker"]==key]["cik"].values[0]
    if len(cik) <10:
        cik = '0' * (10 - len(cik)) +cik
    my_dict[key] = cik

In [28]:
my_dict

{'aapl': '0000320193',
 'msft': '0000789019',
 'brk-b': '0001067983',
 'unh': '0000731766',
 'jnj': '0000200406',
 'v': '0001403161',
 'tsm': '0001046179',
 'xom': '0000034088',
 'wmt': '0000104169',
 'spy': '0000884394',
 'jpm': '0000019617',
 'pg': '0000080424',
 'nvda': '0001045810',
 'lvmuy': '0000824046',
 'ma': '0001141391',
 'cvx': '0000093410',
 'tsla': '0001318605',
 'lly': '0000059478',
 'hd': '0000354950',
 'bac': '0000070858',
 'pfe': '0000078003',
 'ko': '0000021344',
 'abbv': '0001551152',
 'baba': '0001577552',
 'nvo': '0000353278',
 'pep': '0000077476',
 'cost': '0000909832',
 'mrk': '0000310158',
 'tmo': '0000097745',
 'avgo': '0001730168',
 'dhr': '0000313616',
 'dis': '0001744489',
 'tm': '0001094517',
 'mcd': '0000063908',
 'asml': '0000937966',
 'orcl': '0001341439',
 'abt': '0000001800',
 'csco': '0000858877',
 'nvs': '0001114448',
 'azn': '0000901832',
 'tmus': '0001283699',
 'wfc': '0000072971',
 'acn': '0001467373',
 'vz': '0000732712',
 'nee': '0000753308',
 'nke': '0000320187',
 'ups': '0001090727',
 'bmy': '0000014272',
 'ms': '0000895421',
 'cmcsa': '0001166691',
 'crm': '0001108524',
 'cop': '0001163165',
 'txn': '0000097476',
 'adbe': '0000796343',
 'pm': '0001413329',
 'lin': '0001707925',
 'unp': '0000100885',
 'qcom': '0000804328',
 'ry': '0001000275',
 'schw': '0000316709',
 'cvs': '0000064803',
 'bhp': '0000811809',
 'tte': '0000879764',
 'low': '0000060667',
 'amgn': '0000318154',
 'rtx': '0000101829',
 'asti': '0001350102',
 'hsbc': '0001089113',
 'hdb': '0001144967',
 'mdt': '0001613103',
 'hon': '0000773840',
 'td': '0000947263',
 'axp': '0000004962',
 't': '0000732717',
 'intu': '0000896878',
 'intc': '0000050863',
 'eqnr': '0001140625',
 'ul': '0000217410',
 'qqq': '0001067839',
 'lmt': '0000936468',
 'pypl': '0001633917',
 'ibm': '0000051143',
 'amt': '0001053507',
 'gs': '0000886982',
 'de': '0000315189',
 'sbux': '0000829224',
 'nflx': '0001065280',
 'bp': '0000313807',
 'sny': '0001121404',
 'deo': '0000835403',
 'sap': '0001000184',
 'cat': '0000018230',
 'adp': '0000008670',
 'rtntf': '0000887028',
 'c': '0000831001',
 'ci': '0001739940',
 'blk': '0001364742',
 'jd': '0001549802',
 'amd': '0000002488',
 'cslly': '0001274152',
 'bti': '0001303523',
 'sony': '0000313838',
 'rio': '0000863064',
 'el': '0001001250',
 'ba': '0000012927',
 'now': '0001373715',
 'pbr': '0001119639',
 'pld': '0001045609',
 'bud': '0001668717',
 'pdd': '0001737806',
 'syk': '0000310764',
 'enb': '0000895728',
 'cni': '0000016868',
 'spgi': '0000064040',
 'mdlz': '0001103982',
 'cb': '0000896159',
 'so': '0000092122',
 'duk': '0001326160',
 'gild': '0000882095',
 'ibn': '0001103838',
 'bkng': '0001075531',
 'abnb': '0001559720',
 'mmc': '0000062709',
 'tgt': '0000027419',
 'amat': '0000006951',
 'gsk': '0001131399',
 'adi': '0000006281',
 'tjx': '0000109198',
 'mo': '0000764180',
 'bam': '0001001085',
 'noc': '0001133421',
 'regn': '0000872589',
 'infy': '0001067491',
 'ge': '0000040545',
 'glncy': '0001524684',
 'zts': '0001555280',
 'isrg': '0001035267',
 'eadsy': '0001378580',
 'pgr': '0000080661',
 'bdx': '0000010795',
 'vrtx': '0000875320',
 'eog': '0000821189',
 'wm': '0000823768',
 'pbcry': '0001463157',
 'cp': '0000016875',
 'idexy': '0001438656',
 'cci': '0001051470',
 'pnc': '0000713676',
 'fisv': '0000798354',
 'cme': '0001156375',
 'googl': '0001652044',
 'usb': '0000036104',
 'chtr': '0001091667',
 'bx': '0001393818',
 'mmm': '0000066740',
 'csx': '0000277948',
 'mufg': '0000067088',
 'bns': '0000009631',
 'd': '0000715957',
 'hca': '0000860730',
 'sftby': '0001065521',
 'uber': '0001543151',
 'tfc': '0000092230',
 'amzn': '0001018724',
 'team': '0001650372',
 'hum': '0000049071',
 'gd': '0000040533',
 'cnq': '0001017413',
 'cl': '0000021665',
 'vale': '0000917851',
 'bmo': '0000927971',
 'aon': '0000315293',
 'dmlry': '0001067318',
 'itw': '0000049826',
 'oxy': '0000797468',
 'snow': '0001640147',
 'bsx': '0000885725',
 'atvi': '0000718877',
 'cta-pa': '0000030554',
 'pxd': '0001038357',
 'f': '0000037996',
 'ew': '0001099800',
 'mpc': '0001510295',
 'gm': '0001467858',
 'mu': '0000723125',
 'shw': '0000089800',
 'lrcx': '0000707549',
 'nsc': '0000702165',
 'ubs': '0001610520',
 'ntes': '0001110646',
 'epd': '0001061219',
 'etn': '0001551182',
 'dg': '0000029534',
 'slb': '0000087347',
 'abb': '0001091587',
 'eqix': '0001101239',
 'ice': '0001571949',
 'met': '0001099219',
 'mrna': '0001682852',
 'apd': '0000002969',
 'psa': '0001393311',
 'sre': '0001032208',
 'tri': '0001075124',
 'fdx': '0001048911',
 'amov': '0001129137',
 'mar': '0001048286',
 'kdp': '0001418135',
 'rbgly': '0001420798',
 'mco': '0001059556',
 'fis': '0001136893',
 'mck': '0000927653',
 'klac': '0000319201',
 'ntr': '0001725964',
 'cnc': '0001071739',
 'aep': '0000004904',
 'itub': '0001132597',
 'enlay': '0001096200',
 'race': '0001648416',
 'relx': '0000929869',
 'meli': '0001099590',
 'prndy': '0000899108',
 'snps': '0000883241',
 'cmg': '0001058090',
 'emr': '0000032604',
 'vmw': '0001124610',
 'adm': '0000007084',
 'dvn': '0001090012',
 'trp': '0001232384',
 'orly': '0000898173',
 'ecl': '0000031462',
 'mnst': '0000865752',
 'rsg': '0001060391',
 'su': '0000311337',
 'gis': '0000040704',
 'ctva': '0001755672',
 'hsy': '0000047111',
 'cdns': '0000813672',
 'abev': '0001565025',
 'stz': '0000016918',
 'aig': '0000005272',
 'bidu': '0001329099',
 'san': '0000891478',
 'lhx': '0000202058',
 'edu': '0001372920',
 'adsk': '0000769397',
 'azo': '0000866787',
 'lulu': '0001397187',
 'cof': '0000927628',
 'fcx': '0000831259',
 'lng': '0000003570',
 'aph': '0000820313',
 'ngg': '0001004315',
 'vlo': '0001035002',
 'payx': '0000723531',
 'bsbr': '0001471055',
 'hmc': '0000715153',
 'nxpi': '0001413447',
 'stla': '0001605484',
 'khc': '0001637459',
 'bce': '0000718940',
 'exc': '0001109357',
 'enph': '0001463101',
 'tak': '0001395064',
 'kmi': '0001506307',
 'ctas': '0000723254',
 'smfg': '0001022837',
 'crwd': '0001535527',
 'e': '0001002242',
 'kmb': '0000055785',
 'syy': '0000096021',
 'tel': '0001385157',
 'rop': '0000882835',
 'trv': '0000086312',
 'gld': '0001222333',
 'msi': '0000068505',
 'a': '0001090872',
 'wmb': '0000107263',
 'iqv': '0001478242',
 'xel': '0000072903',
 'afl': '0000004977',
 'mrvl': '0001835632',
 'jci': '0000833444',
 'lyg': '0001160106',
 'hes': '0000004447',
 'wday': '0001327811',
 'wcn': '0001318220',
 'et': '0001276187',
 'ajg': '0000354190',
 'gpn': '0001123360',
 'cve': '0001475260',
 'tt': '0001466258',
 'hlt': '0001585689',
 'msci': '0001408198',
 'ing': '0001039765',
 'all': '0000899051',
 'bk': '0001390777',
 'bf-a': '0000014693',
 'scco': '0001001838',
 'nwg': '0000844150',
 'anet': '0001596532',
 'o': '0000726728',
 'psx': '0001534701',
 'mchp': '0000827054',
 'bbd': '0001160330',
 'kr': '0000056873',
 'ea': '0000712515',
 'rivn': '0001874178',
 'carr': '0001783180',
 'pru': '0001137774',
 'bntx': '0001776985',
 'dow': '0001751788',
 'ed': '0001047862',
 'ph': '0000076334',
 'apo': '0001858681',
 'nio': '0001736541',
 'vod': '0000839923',
 'se': '0001703399',
 'nem': '0001164727',
 'yum': '0001041061',
 'twtr': '0001418091',
 'peg': '0000788784',
 'mplx': '0001552000',
 'bcs': '0000312069',
 'mfc': '0001086888',
 'alb': '0000915913',
 'nue': '0000073309',
 'sbac': '0001034054',
 'alc': '0001167379',
 'ctsh': '0001058290',
 'rmd': '0000943819',
 'spg': '0001063761',
 'tdg': '0001260221',
 'stm': '0000932787',
 'bbva': '0000842180',
 'ttd': '0001671933',
 'imo': '0000049938',
 'ifnny': '0001107457',
 'cpng': '0001834584',
 'sq': '0001512673',
 'wec': '0000783325',
 'dlr': '0001297996',
 'well': '0000766704',
 'danoy': '0001048515',
 'rost': '0000745732',
 'ilmn': '0001110803',
 'gfs': '0001709048',
 'amp': '0000820027',
 'dltr': '0000935703',
 'iau': '0001278680',
 'biib': '0000875045',
 'puk': '0001116578',
 'lvs': '0001300514',
 'keys': '0001601046',
 'es': '0000072741',
 'cmi': '0000026172',
 'sqm': '0000909037',
 'ddog': '0001561550',
 'pcar': '0000075362',
 'idxx': '0000874716',
 'vrsk': '0001442145',
 'dfs': '0001393612',
 'wba': '0001618921',
 'bax': '0000010456',
 'tlk': '0001001807',
 'pcg': '0001004980',
 'odfl': '0000878927',
 'tu': '0000868675',
 'on': '0001097864',
 'otis': '0001781335',
 'cht': '0001132924',
 'hpq': '0000047217',
 'abc': '0001140859',
 'ibkr': '0001381197',
 'kkr': '0001404912',
 'mfg': '0001335730',
 'ppery': '0001461748',
 'hcmly': '0000948696',
 'dell': '0001571996',
 'csgp': '0001057352',
 'ppg': '0000079879',
 'mtd': '0001037646',
 'dd': '0001666700',
 'rok': '0001024478',
 'expgy': '0001376891',
 'avb': '0000915912',
 'caixy': '0001535628',
 'ame': '0001037868',
 'baesy': '0000895564',
 'ceg': '0001868275',
 'dnbby': '0001498632',
 'oke': '0001039684',
 'glw': '0000024741',
 'wit': '0001123799',
 'nok': '0000924613',
 'gww': '0000277135',
 'eqr': '0000906107',
 'rweoy': '0000939380',
 'crh': '0000849395',
 'fast': '0000815556',
 'lcid': '0001811210',
 'gold': '0000756894',
 'veev': '0001393052',
 'awk': '0001410636',
 'iff': '0000051253',
 'oran': '0001038143',
 'cqp': '0001383650',
 'ebay': '0001065088',
 'li': '0001791706',
 'hal': '0000045012',
 'frc': '0001132979',
 'cprt': '0000900075',
 'lyb': '0001489393',
 'cbre': '0001138118',
 'tsn': '0000100493',
 'aptv': '0001521332',
 'stt': '0000093751',
 'eix': '0000827052',
 'clr': '0000732834',
 'sgen': '0001060736',
 'slf': '0001097362',
 'trow': '0001113169',
 'nu': '0001691493',
 'dte': '0000936340',
 'dia': '0001041130',
 'rblx': '0001315098',
 'ferg': '0001832433',
 'ctra': '0000858470',
 'exr': '0001289490',
 'alny': '0001178670',
 'hrl': '0000048465',
 'it': '0000749251',
 'dhi': '0000882184',
 'zs': '0001713683',
 'mdy': '0000936958',
 'fitb': '0000035527',
 'fang': '0001539838',
 'zbh': '0001136869',
 'mtb': '0000036270',
 'k': '0000055067',
 'wegzy': '0001445166',
 'gmab': '0001434265',
 'arzgy': '0001379235',
 'zm': '0001585521',
 'caj': '0000016988',
 'siri': '0000908937',
 'fmx': '0001061736',
 'aee': '0001002910',
 'wy': '0000106535',
 'epam': '0001352010',
 'are': '0001035443',
 'etr': '0000065984',
 'ckhuy': '0001637120',
 'ftv': '0001659166',
 'fe': '0001031296',
 'cdw': '0001402057',
 'ulta': '0001403568',
 'zto': '0001677250',
 'vwdry': '0001330306',
 'efx': '0000033185',
 'eric': '0000717826',
 'wtw': '0001140536',
 'fnv': '0001456346',
 'len': '0000920760',
 'hig': '0000874766',
 'rjf': '0000720005',
 'sivb': '0000719739',
 'lgfry': '0001554394',
 'gwlif': '0000850918',
 'invh': '0001687229',
 'dash': '0001792789',
 'tef': '0000814052',
 'gpc': '0000040987',
 'lnngy': '0001447629',
 'cm': '0001045520',
 'luv': '0000092380',
 'ccep': '0001650107',
 'cf': '0001324404',
 'ppl': '0000922224',
 'yumc': '0001673358',
 'vmc': '0001396009',
 'net': '0001477333',
 'lh': '0000920148',
 'ec': '0001444406',
 'tsco': '0000916365',
 'rf': '0001281761',
 'dal': '0000027904',
 'rci': '0000733099',
 'bkr': '0001701605',
 'ttm': '0000926042',
 'payc': '0001590955',
 'anss': '0001013462',
 'mlm': '0000916076',
 'codyy': '0001012037',
 'hban': '0000049196',
 'mkc': '0000063754',
 'dre': '0000783280',
 'uri': '0001067701',
 'mro': '0000101778',
 'vici': '0001705696',
 'lyv': '0001335258',
 'pfg': '0001126328',
 'poahy': '0001450346',
 'fts': '0001666175',
 'wst': '0000105770',
 'cnp': '0001130310',
 'coin': '0001679788',
 'tscdy': '0000885834',
 'ir': '0001699150',
 'moh': '0001179929',
 'ste': '0001757898',
 'mt': '0001243429',
 'spot': '0001639920',
 'algn': '0001097149',
 'mos': '0001285785',
 'ntrs': '0000073124',
 'argx': '0001697862',
 'pwr': '0001050915',
 'pba': '0001546066',
 'vrsn': '0001014473',
 'mpwr': '0001280452',
 'cms': '0000811156',
 'hei': '0000046619',
 'chd': '0000313927',
 'db': '0001159508',
 'ptaiy': '0001455967',
 'snap': '0001564408',
 'maa': '0000912595',
 'br': '0001383312',
 'agr': '0001634997',
 'atasy': '0001437775',
 'foxa': '0001754301',
 'vtr': '0000740260',
 'gib': '0001061574',
 'ix': '0001070304',
 'ui': '0001511737',
 'cah': '0000721371',
 'lpla': '0001397911',
 'qsr': '0001618756',
 'pcrfy': '0000063271',
 'jbht': '0000728535',
 'acgl': '0000947484',
 'eqt': '0000033213',
 'rprx': '0001802768',
 'amcr': '0001748790',
 'wat': '0001000697',
 'podd': '0001145197',
 'syf': '0001601712',
 'aes': '0000874761',
 'panw': '0001327567',
 'zi': '0001794515',
 'anyyy': '0001700171',
 'sui': '0000912593',
 'dov': '0000029905',
 'rol': '0000084839',
 'bby': '0000764478',
 'tdy': '0001094285',
 'bro': '0000079282',
 'clx': '0000021076',
 'teck': '0000886986',
 'bgne': '0001651308',
 'holx': '0000859737',
 'xyl': '0001524472',
 'iclr': '0001060955',
 'ess': '0000920522',
 'dri': '0000940944',
 'hpe': '0001645590',
 'plug': '0001093691',
 'elp': '0001041792',
 'fds': '0001013237',
 'tcom': '0001269238',
 'key': '0000091576',
 'tsgty': '0000939383',
 'grmn': '0001121788',
 'pins': '0001506293',
 'mga': '0000749098',
 'pki': '0000031791',
 'flt': '0001175454',
 'swks': '0000004127',
 'trgp': '0001389170',
 'cnhi': '0001567094',
 'sedg': '0001419612',
 'expd': '0000746515',
 'wab': '0000943452',
 'mtch': '0000891103',
 'expe': '0001324424',
 'bill': '0001786352',
 'mkl': '0001096343',
 'ts': '0001190723',
 'lbrda': '0001611983',
 'bmrn': '0001048477',
 'mgm': '0000789570',
 'cag': '0000023217',
 'cinf': '0000020286',
 'cfg': '0000759944',
 'pltr': '0001321655',
 'swmay': '0001011218',
 'vfc': '0000103379',
 'chkp': '0001015922',
 'zbra': '0000877212',
 'ryaay': '0001038683',
 'csl': '0000790051',
 'umc': '0001033767',
 'iex': '0000832101',
 'snmry': '0001437771',
 'evrg': '0001711269',
 'mdb': '0001441816',
 'phg': '0000313216',
 'wpc': '0001025378',
 'hldcy': '0000811250',
 'irm': '0001020569',
 'j': '0000052988',
 'ip': '0000051434',
 'ntap': '0001002047',
 'ctlt': '0001596783',
 'lsxma': '0001560385',
 'dgx': '0001022079',
 'incy': '0000879169',
 'chwy': '0001766502',
 'ato': '0000731802',
 'stld': '0001022671',
 'lnt': '0000352541',
 'sjm': '0000091419',
 'azpn': '0001897982',
 'rkt': '0001805284',
 'trmb': '0000864749',
 'tw': '0001758730',
 'tyl': '0000860731',
 'avy': '0000008818',
 'splk': '0001353283',
 'coo': '0000711404',
 'ttwo': '0000946581',
 'omc': '0000029989',
 'hwm': '0000004281',
 'smpny': '0001669414',
 'sgioy': '0001281721',
 'hznp': '0001492426',
 'akam': '0001086222',
 'hubs': '0001404655',
 'jkhy': '0000779152',
 'wpm': '0001323404',
 'iep': '0000813762',
 'lkq': '0001065696',
 'etsy': '0001370637',
 'jrony': '0001438077',
 'cpb': '0000016732',
 'bio': '0000012208',
 'avtr': '0001722482',
 'txt': '0000217346',
 'xpev': '0001810997',
 'znh': '0001041668',
 'l': '0000060086',
 'fslr': '0001274494',
 'wmg': '0001319161',
 'chrw': '0001043277',
 'swk': '0000093556',
 'nvr': '0000906163',
 'pcty': '0001591698',
 'stx': '0001137789',
 'udr': '0000074208',
 'twlo': '0001447669',
 'peak': '0000765880',
 'kb': '0001445930',
 'kmx': '0001170010',
 'fmc': '0000037785',
 'tpl': '0001811074',
 'ssnc': '0001402436',
 'wolf': '0000895419',
 'prdsy': '0001527249',
 'ptc': '0000857005',
 'ter': '0000097210',
 'ebr': '0001439124',
 'ovv': '0001792580',
 'viv': '0001066119',
 'cpt': '0000906345',
 'pool': '0000945841',
 'gnrc': '0001474735',
 'shg': '0001263043',
 'tru': '0001552033',
 'apa': '0001841666',
 'ares': '0001176948',
 'kof': '0000910631',
 'els': '0000895417',
 'ndsn': '0000072331',
 'ldos': '0001336920',
 'rcl': '0000884887',
 'hst': '0001070750',
 'bxp': '0001037540',
 'ctxs': '0000877890',
 'aci': '0001646972',
 'rgen': '0000730272',
 'bg': '0001144519',
 'frfhf': '0000915191',
 'nice': '0001003935',
 'cs': '0001159510',
 'kim': '0000879101',
 'ccl': '0000815097',
 'dpz': '0001286681',
 'cnttq': '0001652499',
 'cboe': '0001374310',
 'fhn': '0000036966',
 'sjr': '0000932872',
 'gddy': '0001609711',
 'entg': '0001101302',
 'bip': '0001406234',
 'pkg': '0000075677',
 'ual': '0000100517',
 'nlok': '0000849399',
 'pkx': '0000889132',
 'fico': '0000814547',
 'ar': '0001433270',
 'cck': '0001219601',
 'tech': '0000842023',
 'bah': '0001443646',
 'ben': '0000038777',
 'atlky': '0000748954',
 'vst': '0001692819',
 'chk': '0000895126',
 'dar': '0000916540',
 'wlk': '0001262823',
 'abmd': '0000815094',
 'hubb': '0000048898',
 'wrb': '0000011544',
 'mas': '0000062996',
 'eqh': '0001333986',
 'docu': '0001261333',
 'amh': '0001562401',
 'htht': '0001483994',
 'rpm': '0000110621',
 'glpi': '0001575965',
 'wdc': '0000106040',
 'emraf': '0001127248',
 'ce': '0001306830',
 'ssl': '0000314590',
 'erie': '0000922621',
 'ptbry': '0001504122',
 'vtrs': '0001792044',
 'wtrg': '0000078128',
 'y': '0000775368',
 'bouyy': '0001445475',
 'ccj': '0001009001',
 'sna': '0000091440',
 'asx': '0001122411',
 'wes': '0001423902',
 'jxhly': '0001487533',
 'cea': '0001030475',
 'ni': '0001111711',
 'aer': '0001378789',
 'lw': '0001679273',
 'fnf': '0001331875',
 'ally': '0000040729',
 'suz': '0000909327',
 'cuk': '0001125259',
 're': '0001095073',
 'cg': '0001527166',
 'rs': '0000861884',
 'nfe': '0001749723',
 'u': '0001810806',
 'afg': '0001042046',
 'dqjcy': '0001446597',
 'tap': '0000024545',
 'grab': '0001855612',
 'dt': '0001773383',
 'mmp': '0001126975',
 'nrg': '0001013871',
 'ipg': '0000051644',
 'xp': '0001787425',
 'emn': '0000915389',
 'tfx': '0000096943',
 'ggg': '0000042888',
 'icl': '0000941221',
 'sbny': '0001288784',
 'snn': '0000845982',
 'has': '0000046080',
 'mgddy': '0000896076',
 'nmr': '0001163653',
 'bldr': '0001316835',
 'nly': '0001043219',
 'bep': '0001533232',
 'wso': '0000105016',
 'ewbc': '0001069157',
 'cma': '0000028412',
 'bki': '0001627014',
 'ihg': '0000858446',
 'aap': '0001158449',
 'zshgy': '0001495686',
 'bj': '0001531152',
 'cna': '0000021175',
 'bntgy': '0001533945',
 'gl': '0000320335',
 'crl': '0001100682',
 'h': '0001468174',
 'tost': '0001650164',
 'uhal': '0000004457',
 'ateyy': '0001158838',
 'qgen': '0001015820',
 'ndaq': '0001120193',
 'nwsa': '0001564708',
 'acm': '0000868857',
 'wrk': '0001732845',
 'bap': '0001001290',
 'nbix': '0000914475',
 'wpp': '0000806968',
 'lbtya': '0001570585',
 'wsm': '0000719955',
 'dox': '0001062579',
 'aem': '0000002809',
 'sci': '0000089089',
 'swav': '0001642545',
 'reg': '0000910606',
 'nlsn': '0001492633',
 'hsic': '0001000228',
 'czr': '0001590895',
 'uthr': '0001082554',
 'roku': '0001428439',
 'dks': '0001089063',
 'bhvn': '0001689813',
 'jhx': '0001159152',
 'rrx': '0000082811',
 'phm': '0000822416',
 'fms': '0001333141',
 'agl': '0001831097',
 'morn': '0001289419',
 'teva': '0000818686',
 'bsy': '0001031308',
 'gfl': '0001780232',
 'mktx': '0001278021',
 'okta': '0001660134',
 'armk': '0001584509',
 'gshn': '0001639327',
 'lsi': '0000944314',
 'srpt': '0000873303',
 'bbwi': '0000701985',
 'dbrg': '0001679688',
 'wms': '0001604028',
 'lamr': '0001090425',
 'cube': '0001298675',
 'nvcr': '0001645113',
 'asxfy': '0001449003',
 'dva': '0000927066',
 'wsc': '0001647088',
 'ttc': '0000737758',
 'qrvo': '0001604778',
 'hood': '0001783879',
 'aeg': '0000769218',
 'lnvgy': '0000932477',
 'zg': '0001617640',
 'bch': '0001161125',
 'jazz': '0001232524',
 'deck': '0000910521',
 'mtn': '0000812011',
 'hii': '0001501585',
 'tfii': '0001588823',
 'zen': '0001463172',
 'burl': '0001579298',
 'aal': '0000006201',
 'zion': '0000109380',
 'ffiv': '0001048695',
 'lumn': '0000018926',
 'lii': '0001069202',
 'dish': '0001001082',
 'tpr': '0001116132',
 'car': '0000723612',
 'app': '0001751008',
 'cday': '0001725057',
 'jnpr': '0001043604',
 'bdnny': '0001446457',
 'glob': '0001557860',
 'bz': '0001842827',
 'rexr': '0001571283',
 'cfr': '0000039263',
 'aqn': '0001174169',
 'htz': '0001657853',
 'vivhy': '0001127055',
 'lnc': '0000059558',
 'bwa': '0000908255',
 'aiz': '0001267238',
 'manh': '0001056696',
 'whr': '0000106640',
 'lu': '0001816007',
 'kep': '0000887225',
 'rga': '0000898174',
 'dxcm': '0001093557',
 'arcc': '0001287750',
 'dscsy': '0001671750',
 'snx': '0001177394',
 'stor': '0001538990',
 'paa': '0001070423',
 'eslt': '0001027664',
 'gtlb': '0001653482',
 'rhi': '0000315213',
 'wfg': '0001402388',
 'glpey': '0001385535',
 'rdy': '0001135951',
 'masi': '0000937556',
 'cbsh': '0000022356',

In [29]:
import json
with open('../data/tickers.json', 'w') as f:
    json.dump(my_dict, f)

In [40]:
from sec_edgar_api import EdgarClient

edgar = EdgarClient(user_agent="k")

In [42]:
edgar.get_submissions(cik="320193")

{'cik': '320193',
 'entityType': 'operating',
 'sic': '3571',
 'sicDescription': 'Electronic Computers',
 'insiderTransactionForOwnerExists': 0,
 'insiderTransactionForIssuerExists': 1,
 'name': 'Apple Inc.',
 'tickers': ['AAPL'],
 'exchanges': ['Nasdaq'],
 'ein': '942404110',
 'description': '',
 'website': '',
 'investorWebsite': '',
 'category': 'Large accelerated filer',
 'fiscalYearEnd': '0928',
 'stateOfIncorporation': 'CA',
 'stateOfIncorporationDescription': 'CA',
 'addresses': {'mailing': {'street1': 'ONE APPLE PARK WAY',
   'street2': None,
   'city': 'CUPERTINO',
   'stateOrCountry': 'CA',
   'zipCode': '95014',
   'stateOrCountryDescription': 'CA'},
  'business': {'street1': 'ONE APPLE PARK WAY',
   'street2': None,
   'city': 'CUPERTINO',
   'stateOrCountry': 'CA',
   'zipCode': '95014',
   'stateOrCountryDescription': 'CA'}},
 'phone': '(408) 996-1010',
 'flags': '',
 'formerNames': [{'name': 'APPLE INC',
   'from': '2007-01-10T00:00:00.000Z',
   'to': '2019-08-05T00:00:00.000Z'},
  {'name': 'APPLE COMPUTER INC',
   'from': '1994-01-26T00:00:00.000Z',
   'to': '2007-01-04T00:00:00.000Z'},
  {'name': 'APPLE COMPUTER INC/ FA',
   'from': '1997-07-28T00:00:00.000Z',
   'to': '1997-07-28T00:00:00.000Z'}],
 'filings': {'recent': {'accessionNumber': ['0001140361-24-038601',
    '0001140361-24-038403',
    '0000320193-24-000088',
    '0000320193-24-000086',
    '0000320193-24-000084',
    '0001950047-24-005824',
    '0000320193-24-000081',
    '0000320193-24-000080',
    '0000320193-24-000075',
    '0001921094-24-000702',
    '0000320193-24-000073',
    '0000000000-24-005673',
    '0000320193-24-000071',
    '0001140361-24-024352',
    '0000320193-24-000069',
    '0000320193-24-000067',
    '0000320193-24-000061',
    '0000320193-24-000058',
    '0000320193-24-000056',
    '0000320193-24-000055',
    '0001958244-24-001666',
    '0001973141-24-000220',
    '0001140361-24-018378',
    '0000320193-24-000052',
    '0000320193-24-000051',
    '0000320193-24-000050',
    '0000320193-24-000049',
    '0000320193-24-000048',
    '0001973141-24-000208',
    '0001950047-24-002876',
    '0001959173-24-002769',
    '0000000000-24-003505',
    '0001140361-24-015633',
    '0000320193-24-000042',
    '0000000000-24-002512',
    '0000320193-24-000039',
    '0000320193-24-000038',
    '0000320193-24-000037',
    '0000320193-24-000036',
    '0000320193-24-000035',
    '0000320193-24-000034',
    '0000320193-24-000033',
    '0000320193-24-000032',
    '0001921094-24-000276',
    '0001140361-24-010155',
    '0001193125-24-036431',
    '0001104659-24-020009',
    '0001086364-24-006980',
    '0001096906-24-000181',
    '0000320193-24-000022',
    '0000320193-24-000021',
    '0000320193-24-000020',
    '0000320193-24-000019',
    '0000320193-24-000018',
    '0000320193-24-000017',
    '0000320193-24-000016',
    '0000320193-24-000015',
    '0001096906-24-000156',
    '0001096906-24-000151',
    '0000320193-24-000006',
    '0000320193-24-000005',
    '0001096906-24-000149',
    '0001096906-24-000148',
    '0001096906-24-000147',
    '0001096906-24-000145',
    '0001214659-24-001028',
    '0001354457-24-000017',
    '0001308179-24-000011',
    '0001308179-24-000010',
    '0000320193-23-000113',
    '0000320193-23-000111',
    '0000320193-23-000109',
    '0000320193-23-000106',
    '0000320193-23-000104',
    '0000320193-23-000099',
    '0000320193-23-000097',
    '0000320193-23-000096',
    '0001958244-23-001819',
    '0001958244-23-001817',
    '0001973141-23-000238',
    '0000320193-23-000093',
    '0000320193-23-000092',
    '0000320193-23-000091',
    '0000320193-23-000090',
    '0000320193-23-000089',
    '0000320193-23-000088',
    '0001950047-23-004374',
    '0001973141-23-000233',
    '0001959173-23-004170',
    '0000320193-23-000081',
    '0000320193-23-000079',
    '0001973141-23-000171',
    '0000320193-23-000077',
    '0000320193-23-000075',
    '0000320193-23-000070',
    '0000320193-23-000068',
    '0000320193-23-000066',
    '0001140361-23-023909',
    '0001140361-23-023700',
    '0001140361-23-023544',
    '0001140361-23-023333',
    '0000320193-23-000064',
    '0000320193-23-000063',
    '0000320193-23-000057',
    '0000320193-23-000055',
    '0001958244-23-000454',
    '0000320193-23-000053',
    '0001958244-23-000440',
    '0000320193-23-000051',
    '0000320193-23-000050',
    '0000320193-23-000049',
    '0000320193-23-000048',
    '0000320193-23-000047',
    '0000320193-23-000040',
    '0001140361-23-012065',
    '0000320193-23-000038',
    '0000320193-23-000037',
    '0000320193-23-000036',
    '0000320193-23-000035',
    '0000320193-23-000034',
    '0000320193-23-000033',
    '0000320193-23-000032',
    '0000320193-23-000031',
    '0001140361-23-011192',
    '0001096906-23-000438',
    '0001096906-23-000437',
    '0001214659-23-002862',
    '0001096906-23-000372',
    '0001193125-23-038262',
    '0001104659-23-015055',
    '0001306550-23-008266',
    '0000320193-23-000022',
    '0000320193-23-000021',
    '0000320193-23-000020',
    '0000320193-23-000019',
    '0000320193-23-000018',
    '0000320193-23-000017',
    '0000320193-23-000016',
    '0000320193-23-000015',
    '0001140361-23-004439',
    '0000320193-23-000006',
    '0000320193-23-000005',
    '0001214659-23-001246',
    '0001214659-23-000970',
    '0001308179-23-000020',
    '0001308179-23-000019',
    '0000320193-22-000113',
    '0001354457-22-000638',
    '0001193125-22-278435',
    '0000320193-22-000111',
    '0000320193-22-000108',
    '0000320193-22-000107',
    '0000320193-22-000102',
    '0000320193-22-000101',
    '0000320193-22-000097',
    '0000320193-22-000095',
    '0000320193-22-000096',
    '0000320193-22-000098',
    '0000320193-22-000090',
    '0000320193-22-000089',
    '0000320193-22-000088',
    '0000320193-22-000087',
    '0000320193-22-000086',
    '0000320193-22-000085',
    '0000320193-22-000078',
    '0000320193-22-000076',
    '0001193125-22-225365',
    '0000320193-22-000074',
    '0001193125-22-214914',
    '0000320193-22-000072',
    '0001193125-22-210056',
    '0001193125-22-209084',
    '0001193125-22-207773',
    '0000320193-22-000070',
    '0000320193-22-000069',
    '0000320193-22-000063',
    '0000320193-22-000061',
    '0001193125-22-128368',
    '0001193125-22-128361',
    '0001193125-22-128354',
    '0000320193-22-000059',
    '0000320193-22-000058',
    '0000320193-22-000053',
    '0000320193-22-000052',
    '0000320193-22-000049',
    '0000320193-22-000048',
    '0000320193-22-000047',
    '0000320193-22-000046',
    '0000320193-22-000041',
    '0000320193-22-000040',
    '0000320193-22-000039',
    '0000320193-22-000038',
    '0000320193-22-000037',
    '0000320193-22-000036',
    '0000320193-22-000035',
    '0000320193-22-000034',
    '0001193125-22-066169',
    '0001193125-22-032738',
    '0001104659-22-016224',
    '0001214659-22-002092',
    '0000320193-22-000025',
    '0000320193-22-000023',
    '0000320193-22-000022',
    '0000320193-22-000021',
    '0000320193-22-000020',
    '0000320193-22-000019',
    '0000320193-22-000018',
    '0000320193-22-000017',
    '0000320193-22-000016',
    '0001214659-22-001589',
    '0001214659-22-001473',
    '0000834237-22-004076',
    '0001214659-22-001295',
    '0000320193-22-000007',
    '0000320193-22-000006',
    '0001377739-22-000005',
    '0001193125-22-003593',
    '0001193125-22-003583',
    '0000320193-21-000114',
    '0000320193-21-000112',
    '0000320193-21-000111',
    '0001193125-21-328151',
    '0000320193-21-000108',
    '0001193125-21-312274',
    '0001193125-21-311635',
    '0000320193-21-000105',
    '0000320193-21-000104',
    '0000320193-21-000099',
    '0000320193-21-000097',
    '0000320193-21-000096',
    '0000320193-21-000093',
    '0000320193-21-000092',
    '0000320193-21-000091',
    '0000320193-21-000090',
    '0000320193-21-000085',
    '0000320193-21-000084',
    '0000320193-21-000083',
    '0000320193-21-000082',
    '0000320193-21-000081',
    '0000320193-21-000080',
    '0000320193-21-000073',
    '0000320193-21-000071',
    '0000320193-21-000069',
    '0001193125-21-237787',
    '0000320193-21-000067',
    '0001193125-21-231584',
    '0001193125-21-229470',
    '0001193125-21-228285',
    '0001193125-21-225983',
    '0000320193-21-000065',
    '0000320193-21-000063',
    '0000320193-21-000060',
    '0000320193-21-000059',
    '0000320193-21-000056',
    '0000320193-21-000055',
    '0000320193-21-000050',
    '0000320193-21-000049',
    '0000320193-21-000046',
    '0000320193-21-000045',
    '0000320193-21-000044',
    '0000320193-21-000040',
    '0000320193-21-000039',
    '0000320193-21-000038',
    '0000320193-21-000037',
    '0000320193-21-000036',
    '0000320193-21-000035',
    '0000320193-21-000034',
    '0001193125-21-054710',
    '0001214659-21-002046',
    '0001193125-21-044816',
    '0001193125-21-036337',
    '0001104659-21-017199',
    '0001193125-21-032394',
    '0000834237-21-007542',
    '0000320193-21-000026',
    '0000320193-21-000025',
    '0000320193-21-000024',
    '0000320193-21-000023',
    '0000320193-21-000022',
    '0000320193-21-000021',
    '0000320193-21-000020',
    '0000320193-21-000019',
    '0001193125-21-025910',
    '0001193125-21-024892',
    '0001193125-21-023836',
    '0000320193-21-000010',
    '0000320193-21-000009',
    '0000320193-21-000004',
    '0000320193-21-000003',
    '0001193125-21-001989',
    '0001193125-21-001987',
    '0001193125-21-001982',
    '0000320193-20-000101',
    '0000320193-20-000099',
    '0000320193-20-000096',
    '0000320193-20-000094',
    '0000320193-20-000090',
    '0000320193-20-000089',
    '0000320193-20-000086',
    '0000320193-20-000084',
    '0000320193-20-000083',
    '0000320193-20-000082',
    '0000320193-20-000078',
    '0000320193-20-000077',
    '0000320193-20-000076',
    '0000320193-20-000075',
    '0000320193-20-000074',
    '0000320193-20-000073',
    '0000320193-20-000066',
    '0000320193-20-000064',
    '0001193125-20-225672',
    '0001193125-20-220410',
    '0001193125-20-219289',
    '0001193125-20-218350',
    '0001193125-20-213158',
    '0000320193-20-000062',
    '0000320193-20-000060',
    '0000320193-20-000056',
    '0001193125-20-139112',
    '0001193125-20-133777',
    '0001193125-20-132661',
    '0001193125-20-131780',
    '0000320193-20-000052',
    '0000320193-20-000054',
    '0000320193-20-000050',
    '0000320193-20-000045',
    '0000320193-20-000044',
    '0000320193-20-000041',
    '0000320193-20-000039',
    '0000320193-20-000038',
    '0000320193-20-000035',
    '0000320193-20-000034',
    '0000320193-20-000033',
    '0000320193-20-000032',
    '0000320193-20-000031',
    '0000320193-20-000030',
    '0001193125-20-050884',
    '0001193125-20-039203',
    '0001193125-20-038381',
    '0001104659-20-018528',
    '0000834237-20-008795',
    '0001193125-20-026822',
    '0000320193-20-000023',
    '0000320193-20-000022',
    '0000320193-20-000021',
    '0000320193-20-000020',
    '0000320193-20-000019',
    '0000320193-20-000018',
    '0000320193-20-000011',
    '0000320193-20-000010',
    '0000320193-20-000008',
    '0001214659-20-000610',
    '0001387131-20-000386',
    '0001193125-20-001452',
    '0001193125-20-001450',
    '0000320193-20-000002',
    '0001354457-19-000604',
    '0001193125-19-292825',
    '0001193125-19-292676',
    '0000320193-19-000123',
    '0001193125-19-288412',
    '0000320193-19-000121',
    '0001193125-19-287351',
    '0001193125-19-286514',
    '0001193125-19-280516',
    '0000320193-19-000119',
    '0000320193-19-000117',
    '0000320193-19-000113',
    '0000320193-19-000112',
    '0000320193-19-000109',
    '0000320193-19-000107',
    '0000320193-19-000106',
    '0000320193-19-000103',
    '0000320193-19-000102',
    '0000320193-19-000101',
    '0000320193-19-000100',
    '0000320193-19-000099',
    '0000320193-19-000093',
    '0001193125-19-242975',
    '0001193125-19-238922',
    '0001193125-19-237993',
    '0001193125-19-237090',
    '0000320193-19-000090',
    '0000320193-19-000088',
    '0000320193-19-000086',
    '0000320193-19-000082',
    '0000320193-19-000081',
    '0000320193-19-000080',
    '0000320193-19-000076',
    '0000320193-19-000073',
    '0000320193-19-000070',
    '0000320193-19-000069',
    '0000320193-19-000066',
    '0000320193-19-000063',
    '0000320193-19-000060',
    '0000320193-19-000059',
    '0000320193-19-000058',
    '0000320193-19-000054',
    '0000320193-19-000052',
    '0000320193-19-000051',
    '0001354457-19-000130',
    '0001193125-19-074874',
    '0001193125-19-074868',
    '0000320193-19-000046',
    '0000320193-19-000045',
    '0000320193-19-000044',
    '0000320193-19-000043',
    '0000320193-19-000042',
    '0000320193-19-000041',
    '0000320193-19-000040',
    '0000320193-19-000032',
    '0001193125-19-041571',
    '0001193125-19-041014',
    '0000932471-19-004418',
    '0000320193-19-000030',
    '0000320193-19-000029',
    '0000320193-19-000026',
    '0000320193-19-000024',
    '0000320193-19-000023',
    '0000320193-19-000022',
    '0000320193-19-000021',
    '0000320193-19-000020',
    '0000320193-19-000019',
    '0000320193-19-000018',
    '0001214659-19-000797',
    '0000215457-19-003343',
    '0000320193-19-000010',
    '0000320193-19-000007',
    '0000320193-19-000004',
    '0001193125-19-004678',
    '0001193125-19-004664',
    '0000320193-19-000002',
    '0000320193-18-000149',
    '0000320193-18-000147',
    '0001193125-18-317844',
    '0000320193-18-000145',
    '0000320193-18-000142',
    '0000320193-18-000139',
    '0000320193-18-000137',
    '0000320193-18-000136',
    '0000320193-18-000135',
    '0000320193-18-000131',
    '0000320193-18-000130',
    '0000320193-18-000129',
    '0000320193-18-000125',
    '0000320193-18-000124',
    '0000320193-18-000123',
    '0000320193-18-000122',
    '0000320193-18-000121',
    '0000320193-18-000115',
    '0001193125-18-256354',
    '0000320193-18-000113',
    '0000320193-18-000112',
    '0000320193-18-000109',
    '0000320193-18-000107',
    '0000320193-18-000106',
    '0000320193-18-000103',
    '0000320193-18-000100',
    '0000320193-18-000098',
    '0000320193-18-000095',
    '0000320193-18-000092',
    '0000320193-18-000090',
    '0000320193-18-000088',
    '0000320193-18-000086',
    '0000320193-18-000084',
    '0000320193-18-000082',
    '0000320193-18-000080',
    '0000320193-18-000078',
    '0000320193-18-000076',
    '0000320193-18-000074',
    '0001193125-18-154948',
    '0000320193-18-000072',
    '0001193125-18-154515',
    '0000320193-18-000070',
    '0000320193-18-000067',
    '0000320193-18-000064',
    '0000320193-18-000063',
    '0000320193-18-000060',
    '0000320193-18-000058',
    '0000320193-18-000057',
    '0000320193-18-000054',
    '0000320193-18-000053',
    '0000320193-18-000052',
    '0000320193-18-000051',
    '0000320193-18-000050',
    '0000320193-18-000049',
    '0000320193-18-000048',
    '0001193125-18-073716',
    '0000320193-18-000040',
    '0000320193-18-000037',
    '0000320193-18-000036',
    '0000320193-18-000035',
    '0000320193-18-000034',
    '0000320193-18-000033',
    '0000320193-18-000032',
    '0000320193-18-000031',
    '0001193125-18-045761',
    '0000932471-18-004625',
    '0000320193-18-000023',
    '0000320193-18-000021',
    '0000320193-18-000020',
    '0000320193-18-000019',
    '0000320193-18-000018',
    '0000320193-18-000017',
    '0000320193-18-000016',
    '0000320193-18-000015',
    '0000320193-18-000007',
    '0000320193-18-000005',
    '0000215457-18-003762',
    '0000320193-18-000002',
    '0001193125-17-380132',
    '0001193125-17-380130',
    '0000320193-17-000087',
    '0000320193-17-000085',
    '0000320193-17-000083',
    '0000320193-17-000081',
    '0000320193-17-000079',
    '0000320193-17-000078',
    '0000320193-17-000077',
    '0001193125-17-341015',
    '0001193125-17-335805',
    '0001193125-17-334724',
    '0001193125-17-333582',
    '0000320193-17-000070',
    '0000320193-17-000067',
    '0000320193-17-000063',
    '0000320193-17-000062',
    '0000320193-17-000061',
    '0000320193-17-000060',
    '0000320193-17-000059',
    '0000320193-17-000058',
    '0000320193-17-000057',
    '0000320193-17-000056',
    '0000320193-17-000055',
    '0001193125-17-308859',
    '0000320193-17-000045',
    '0000320193-17-000043',
    '0000320193-17-000042',
    '0000320193-17-000039',
    '0000320193-17-000038',
    '0000320193-17-000037',
    '0000320193-17-000036',
    '0000320193-17-000035',
    '0000320193-17-000034',
    '0000320193-17-000033',
    '0000320193-17-000032',
    '0001193125-17-282809',
    '0001193125-17-277897',
    '0001193125-17-276961',
    '0001193125-17-276117',
    '0000320193-17-000023',
    '0000320193-17-000021',
    '0000320193-17-000018',
    '0001193125-17-262261',
    '0000320193-17-000017',
    '0001193125-17-258933',
    '0001193125-17-258729',
    '0001193125-17-258040',
    '0000320193-17-000015',
    '0000320193-17-000014',
    '0000320193-17-000013',
    '0000320193-17-000009',
    '0000320193-17-000006',
    '0000320193-17-000003',
    '0001193125-17-208226',
    '0001628280-17-006558',
    '0001193125-17-203548',
    '0001193125-17-202772',
    '0001193125-17-201958',
    '0001628280-17-006357',
    '0001628280-17-006261',
    '0001628280-17-006119',
    '0001628280-17-006040',
    '0001628280-17-005932',
    '9999999997-17-006550',
    '0001628280-17-005877',
    '0001628280-17-005876',
    '0001193125-17-181871',
    '0001193125-17-181867',
    '0001628280-17-005698',
    '0001193125-17-175330',
    '0001193125-17-173678',
    '0001193125-17-172693',
    '0001628280-17-005434',
    '0001628280-17-005433',
    '0001193125-17-167400',
    '0001628280-17-005184',
    '0001628280-17-005183',
    '0001193125-17-160948',
    '0001193125-17-159397',
    '0001193125-17-159324',
    '0001193125-17-157385',
    '0001628280-17-004826',
    '0001628280-17-004790',
    '0001628280-17-004663',
    '0001628280-17-004167',
    '0001628280-17-003836',
    '0001628280-17-003835',
    '0001628280-17-003834',
    '0001628280-17-003444',
    '0001628280-17-003442',
    '0001628280-17-003348',
    '0001628280-17-003347',
    '0001628280-17-003346',
    '0001628280-17-003345',
    '0001628280-17-003344',
    '0001628280-17-003343',
    '0001628280-17-003342',
    '0001628280-17-003341',
    '0001628280-17-002692',
    '0001628280-17-002321',
    '0001193125-17-069853',
    '0001628280-17-002133',
    '0001628280-17-002132',
    '0001628280-17-002131',
    '0001628280-17-002130',
    '0001628280-17-002129',
    '0001628280-17-002128',
    '0001628280-17-002127',
    '0001193125-17-064019',
    '0001628280-17-001737',
    '0001628280-17-001593',
    '0001628280-17-001484',
    '0001628280-17-001483',
    '0001193125-17-044564',
    '0001193125-17-042083',
    '0001193125-17-041233',
    '0001193125-17-036283',
    '0000932471-17-000777',
    '0001628280-17-000963',
    '0001628280-17-000897',
    '0001628280-17-000896',
    '0001628280-17-000895',
    '0001628280-17-000894',
    '0001628280-17-000893',
    '0001628280-17-000892',
    '0001628280-17-000891',
    '0001628280-17-000890',
    '0001628280-17-000889',
    '0001628280-17-000888',
    '0001193125-17-030832',
    '0001193125-17-029548',
    '0001193125-17-028315',
    '0001628280-17-000744',
    '0001628280-17-000717',
    '0001628280-17-000663',
    '0001214659-17-000547',
    '0001628280-17-000550',
    '0001628280-17-000379',
    '0001628280-17-000312',
    '0001628280-17-000311',
    '0000215457-17-001275',
    '0001628280-17-000187',
    '0001193125-17-003764',
    '0001193125-17-003753',
    '0001628280-16-022242',
    '0001628280-16-022104',
    '0001628280-16-022047',
    '0001628280-16-022020',
    '9999999997-17-000002',
    '0001628280-16-021649',
    '0001628280-16-021144',
    '0001628280-16-020880',
    '0001628280-16-020879',
    '0001628280-16-020489',
    '0001628280-16-020488',
    '9999999997-17-000809',
    '9999999997-16-026607',

In [43]:
edgar.get_submissions(cik="320193", handle_pagination=False)

{'cik': '320193',
 'entityType': 'operating',
 'sic': '3571',
 'sicDescription': 'Electronic Computers',
 'insiderTransactionForOwnerExists': 0,
 'insiderTransactionForIssuerExists': 1,
 'name': 'Apple Inc.',
 'tickers': ['AAPL'],
 'exchanges': ['Nasdaq'],
 'ein': '942404110',
 'description': '',
 'website': '',
 'investorWebsite': '',
 'category': 'Large accelerated filer',
 'fiscalYearEnd': '0928',
 'stateOfIncorporation': 'CA',
 'stateOfIncorporationDescription': 'CA',
 'addresses': {'mailing': {'street1': 'ONE APPLE PARK WAY',
   'street2': None,
   'city': 'CUPERTINO',
   'stateOrCountry': 'CA',
   'zipCode': '95014',
   'stateOrCountryDescription': 'CA'},
  'business': {'street1': 'ONE APPLE PARK WAY',
   'street2': None,
   'city': 'CUPERTINO',
   'stateOrCountry': 'CA',
   'zipCode': '95014',
   'stateOrCountryDescription': 'CA'}},
 'phone': '(408) 996-1010',
 'flags': '',
 'formerNames': [{'name': 'APPLE INC',
   'from': '2007-01-10T00:00:00.000Z',
   'to': '2019-08-05T00:00:00.000Z'},
  {'name': 'APPLE COMPUTER INC',
   'from': '1994-01-26T00:00:00.000Z',
   'to': '2007-01-04T00:00:00.000Z'},
  {'name': 'APPLE COMPUTER INC/ FA',
   'from': '1997-07-28T00:00:00.000Z',
   'to': '1997-07-28T00:00:00.000Z'}],
 'filings': {'recent': {'accessionNumber': ['0001140361-24-038601',
    '0001140361-24-038403',
    '0000320193-24-000088',
    '0000320193-24-000086',
    '0000320193-24-000084',
    '0001950047-24-005824',
    '0000320193-24-000081',
    '0000320193-24-000080',
    '0000320193-24-000075',
    '0001921094-24-000702',
    '0000320193-24-000073',
    '0000000000-24-005673',
    '0000320193-24-000071',
    '0001140361-24-024352',
    '0000320193-24-000069',
    '0000320193-24-000067',
    '0000320193-24-000061',
    '0000320193-24-000058',
    '0000320193-24-000056',
    '0000320193-24-000055',
    '0001958244-24-001666',
    '0001973141-24-000220',
    '0001140361-24-018378',
    '0000320193-24-000052',
    '0000320193-24-000051',
    '0000320193-24-000050',
    '0000320193-24-000049',
    '0000320193-24-000048',
    '0001973141-24-000208',
    '0001950047-24-002876',
    '0001959173-24-002769',
    '0000000000-24-003505',
    '0001140361-24-015633',
    '0000320193-24-000042',
    '0000000000-24-002512',
    '0000320193-24-000039',
    '0000320193-24-000038',
    '0000320193-24-000037',
    '0000320193-24-000036',
    '0000320193-24-000035',
    '0000320193-24-000034',
    '0000320193-24-000033',
    '0000320193-24-000032',
    '0001921094-24-000276',
    '0001140361-24-010155',
    '0001193125-24-036431',
    '0001104659-24-020009',
    '0001086364-24-006980',
    '0001096906-24-000181',
    '0000320193-24-000022',
    '0000320193-24-000021',
    '0000320193-24-000020',
    '0000320193-24-000019',
    '0000320193-24-000018',
    '0000320193-24-000017',
    '0000320193-24-000016',
    '0000320193-24-000015',
    '0001096906-24-000156',
    '0001096906-24-000151',
    '0000320193-24-000006',
    '0000320193-24-000005',
    '0001096906-24-000149',
    '0001096906-24-000148',
    '0001096906-24-000147',
    '0001096906-24-000145',
    '0001214659-24-001028',
    '0001354457-24-000017',
    '0001308179-24-000011',
    '0001308179-24-000010',
    '0000320193-23-000113',
    '0000320193-23-000111',
    '0000320193-23-000109',
    '0000320193-23-000106',
    '0000320193-23-000104',
    '0000320193-23-000099',
    '0000320193-23-000097',
    '0000320193-23-000096',
    '0001958244-23-001819',
    '0001958244-23-001817',
    '0001973141-23-000238',
    '0000320193-23-000093',
    '0000320193-23-000092',
    '0000320193-23-000091',
    '0000320193-23-000090',
    '0000320193-23-000089',
    '0000320193-23-000088',
    '0001950047-23-004374',
    '0001973141-23-000233',
    '0001959173-23-004170',
    '0000320193-23-000081',
    '0000320193-23-000079',
    '0001973141-23-000171',
    '0000320193-23-000077',
    '0000320193-23-000075',
    '0000320193-23-000070',
    '0000320193-23-000068',
    '0000320193-23-000066',
    '0001140361-23-023909',
    '0001140361-23-023700',
    '0001140361-23-023544',
    '0001140361-23-023333',
    '0000320193-23-000064',
    '0000320193-23-000063',
    '0000320193-23-000057',
    '0000320193-23-000055',
    '0001958244-23-000454',
    '0000320193-23-000053',
    '0001958244-23-000440',
    '0000320193-23-000051',
    '0000320193-23-000050',
    '0000320193-23-000049',
    '0000320193-23-000048',
    '0000320193-23-000047',
    '0000320193-23-000040',
    '0001140361-23-012065',
    '0000320193-23-000038',
    '0000320193-23-000037',
    '0000320193-23-000036',
    '0000320193-23-000035',
    '0000320193-23-000034',
    '0000320193-23-000033',
    '0000320193-23-000032',
    '0000320193-23-000031',
    '0001140361-23-011192',
    '0001096906-23-000438',
    '0001096906-23-000437',
    '0001214659-23-002862',
    '0001096906-23-000372',
    '0001193125-23-038262',
    '0001104659-23-015055',
    '0001306550-23-008266',
    '0000320193-23-000022',
    '0000320193-23-000021',
    '0000320193-23-000020',
    '0000320193-23-000019',
    '0000320193-23-000018',
    '0000320193-23-000017',
    '0000320193-23-000016',
    '0000320193-23-000015',
    '0001140361-23-004439',
    '0000320193-23-000006',
    '0000320193-23-000005',
    '0001214659-23-001246',
    '0001214659-23-000970',
    '0001308179-23-000020',
    '0001308179-23-000019',
    '0000320193-22-000113',
    '0001354457-22-000638',
    '0001193125-22-278435',
    '0000320193-22-000111',
    '0000320193-22-000108',
    '0000320193-22-000107',
    '0000320193-22-000102',
    '0000320193-22-000101',
    '0000320193-22-000097',
    '0000320193-22-000095',
    '0000320193-22-000096',
    '0000320193-22-000098',
    '0000320193-22-000090',
    '0000320193-22-000089',
    '0000320193-22-000088',
    '0000320193-22-000087',
    '0000320193-22-000086',
    '0000320193-22-000085',
    '0000320193-22-000078',
    '0000320193-22-000076',
    '0001193125-22-225365',
    '0000320193-22-000074',
    '0001193125-22-214914',
    '0000320193-22-000072',
    '0001193125-22-210056',
    '0001193125-22-209084',
    '0001193125-22-207773',
    '0000320193-22-000070',
    '0000320193-22-000069',
    '0000320193-22-000063',
    '0000320193-22-000061',
    '0001193125-22-128368',
    '0001193125-22-128361',
    '0001193125-22-128354',
    '0000320193-22-000059',
    '0000320193-22-000058',
    '0000320193-22-000053',
    '0000320193-22-000052',
    '0000320193-22-000049',
    '0000320193-22-000048',
    '0000320193-22-000047',
    '0000320193-22-000046',
    '0000320193-22-000041',
    '0000320193-22-000040',
    '0000320193-22-000039',
    '0000320193-22-000038',
    '0000320193-22-000037',
    '0000320193-22-000036',
    '0000320193-22-000035',
    '0000320193-22-000034',
    '0001193125-22-066169',
    '0001193125-22-032738',
    '0001104659-22-016224',
    '0001214659-22-002092',
    '0000320193-22-000025',
    '0000320193-22-000023',
    '0000320193-22-000022',
    '0000320193-22-000021',
    '0000320193-22-000020',
    '0000320193-22-000019',
    '0000320193-22-000018',
    '0000320193-22-000017',
    '0000320193-22-000016',
    '0001214659-22-001589',
    '0001214659-22-001473',
    '0000834237-22-004076',
    '0001214659-22-001295',
    '0000320193-22-000007',
    '0000320193-22-000006',
    '0001377739-22-000005',
    '0001193125-22-003593',
    '0001193125-22-003583',
    '0000320193-21-000114',
    '0000320193-21-000112',
    '0000320193-21-000111',
    '0001193125-21-328151',
    '0000320193-21-000108',
    '0001193125-21-312274',
    '0001193125-21-311635',
    '0000320193-21-000105',
    '0000320193-21-000104',
    '0000320193-21-000099',
    '0000320193-21-000097',
    '0000320193-21-000096',
    '0000320193-21-000093',
    '0000320193-21-000092',
    '0000320193-21-000091',
    '0000320193-21-000090',
    '0000320193-21-000085',
    '0000320193-21-000084',
    '0000320193-21-000083',
    '0000320193-21-000082',
    '0000320193-21-000081',
    '0000320193-21-000080',
    '0000320193-21-000073',
    '0000320193-21-000071',
    '0000320193-21-000069',
    '0001193125-21-237787',
    '0000320193-21-000067',
    '0001193125-21-231584',
    '0001193125-21-229470',
    '0001193125-21-228285',
    '0001193125-21-225983',
    '0000320193-21-000065',
    '0000320193-21-000063',
    '0000320193-21-000060',
    '0000320193-21-000059',
    '0000320193-21-000056',
    '0000320193-21-000055',
    '0000320193-21-000050',
    '0000320193-21-000049',
    '0000320193-21-000046',
    '0000320193-21-000045',
    '0000320193-21-000044',
    '0000320193-21-000040',
    '0000320193-21-000039',
    '0000320193-21-000038',
    '0000320193-21-000037',
    '0000320193-21-000036',
    '0000320193-21-000035',
    '0000320193-21-000034',
    '0001193125-21-054710',
    '0001214659-21-002046',
    '0001193125-21-044816',
    '0001193125-21-036337',
    '0001104659-21-017199',
    '0001193125-21-032394',
    '0000834237-21-007542',
    '0000320193-21-000026',
    '0000320193-21-000025',
    '0000320193-21-000024',
    '0000320193-21-000023',
    '0000320193-21-000022',
    '0000320193-21-000021',
    '0000320193-21-000020',
    '0000320193-21-000019',
    '0001193125-21-025910',
    '0001193125-21-024892',
    '0001193125-21-023836',
    '0000320193-21-000010',
    '0000320193-21-000009',
    '0000320193-21-000004',
    '0000320193-21-000003',
    '0001193125-21-001989',
    '0001193125-21-001987',
    '0001193125-21-001982',
    '0000320193-20-000101',
    '0000320193-20-000099',
    '0000320193-20-000096',
    '0000320193-20-000094',
    '0000320193-20-000090',
    '0000320193-20-000089',
    '0000320193-20-000086',
    '0000320193-20-000084',
    '0000320193-20-000083',
    '0000320193-20-000082',
    '0000320193-20-000078',
    '0000320193-20-000077',
    '0000320193-20-000076',
    '0000320193-20-000075',
    '0000320193-20-000074',
    '0000320193-20-000073',
    '0000320193-20-000066',
    '0000320193-20-000064',
    '0001193125-20-225672',
    '0001193125-20-220410',
    '0001193125-20-219289',
    '0001193125-20-218350',
    '0001193125-20-213158',
    '0000320193-20-000062',
    '0000320193-20-000060',
    '0000320193-20-000056',
    '0001193125-20-139112',
    '0001193125-20-133777',
    '0001193125-20-132661',
    '0001193125-20-131780',
    '0000320193-20-000052',
    '0000320193-20-000054',
    '0000320193-20-000050',
    '0000320193-20-000045',
    '0000320193-20-000044',
    '0000320193-20-000041',
    '0000320193-20-000039',
    '0000320193-20-000038',
    '0000320193-20-000035',
    '0000320193-20-000034',
    '0000320193-20-000033',
    '0000320193-20-000032',
    '0000320193-20-000031',
    '0000320193-20-000030',
    '0001193125-20-050884',
    '0001193125-20-039203',
    '0001193125-20-038381',
    '0001104659-20-018528',
    '0000834237-20-008795',
    '0001193125-20-026822',
    '0000320193-20-000023',
    '0000320193-20-000022',
    '0000320193-20-000021',
    '0000320193-20-000020',
    '0000320193-20-000019',
    '0000320193-20-000018',
    '0000320193-20-000011',
    '0000320193-20-000010',
    '0000320193-20-000008',
    '0001214659-20-000610',
    '0001387131-20-000386',
    '0001193125-20-001452',
    '0001193125-20-001450',
    '0000320193-20-000002',
    '0001354457-19-000604',
    '0001193125-19-292825',
    '0001193125-19-292676',
    '0000320193-19-000123',
    '0001193125-19-288412',
    '0000320193-19-000121',
    '0001193125-19-287351',
    '0001193125-19-286514',
    '0001193125-19-280516',
    '0000320193-19-000119',
    '0000320193-19-000117',
    '0000320193-19-000113',
    '0000320193-19-000112',
    '0000320193-19-000109',
    '0000320193-19-000107',
    '0000320193-19-000106',
    '0000320193-19-000103',
    '0000320193-19-000102',
    '0000320193-19-000101',
    '0000320193-19-000100',
    '0000320193-19-000099',
    '0000320193-19-000093',
    '0001193125-19-242975',
    '0001193125-19-238922',
    '0001193125-19-237993',
    '0001193125-19-237090',
    '0000320193-19-000090',
    '0000320193-19-000088',
    '0000320193-19-000086',
    '0000320193-19-000082',
    '0000320193-19-000081',
    '0000320193-19-000080',
    '0000320193-19-000076',
    '0000320193-19-000073',
    '0000320193-19-000070',
    '0000320193-19-000069',
    '0000320193-19-000066',
    '0000320193-19-000063',
    '0000320193-19-000060',
    '0000320193-19-000059',
    '0000320193-19-000058',
    '0000320193-19-000054',
    '0000320193-19-000052',
    '0000320193-19-000051',
    '0001354457-19-000130',
    '0001193125-19-074874',
    '0001193125-19-074868',
    '0000320193-19-000046',
    '0000320193-19-000045',
    '0000320193-19-000044',
    '0000320193-19-000043',
    '0000320193-19-000042',
    '0000320193-19-000041',
    '0000320193-19-000040',
    '0000320193-19-000032',
    '0001193125-19-041571',
    '0001193125-19-041014',
    '0000932471-19-004418',
    '0000320193-19-000030',
    '0000320193-19-000029',
    '0000320193-19-000026',
    '0000320193-19-000024',
    '0000320193-19-000023',
    '0000320193-19-000022',
    '0000320193-19-000021',
    '0000320193-19-000020',
    '0000320193-19-000019',
    '0000320193-19-000018',
    '0001214659-19-000797',
    '0000215457-19-003343',
    '0000320193-19-000010',
    '0000320193-19-000007',
    '0000320193-19-000004',
    '0001193125-19-004678',
    '0001193125-19-004664',
    '0000320193-19-000002',
    '0000320193-18-000149',
    '0000320193-18-000147',
    '0001193125-18-317844',
    '0000320193-18-000145',
    '0000320193-18-000142',
    '0000320193-18-000139',
    '0000320193-18-000137',
    '0000320193-18-000136',
    '0000320193-18-000135',
    '0000320193-18-000131',
    '0000320193-18-000130',
    '0000320193-18-000129',
    '0000320193-18-000125',
    '0000320193-18-000124',
    '0000320193-18-000123',
    '0000320193-18-000122',
    '0000320193-18-000121',
    '0000320193-18-000115',
    '0001193125-18-256354',
    '0000320193-18-000113',
    '0000320193-18-000112',
    '0000320193-18-000109',
    '0000320193-18-000107',
    '0000320193-18-000106',
    '0000320193-18-000103',
    '0000320193-18-000100',
    '0000320193-18-000098',
    '0000320193-18-000095',
    '0000320193-18-000092',
    '0000320193-18-000090',
    '0000320193-18-000088',
    '0000320193-18-000086',
    '0000320193-18-000084',
    '0000320193-18-000082',
    '0000320193-18-000080',
    '0000320193-18-000078',
    '0000320193-18-000076',
    '0000320193-18-000074',
    '0001193125-18-154948',
    '0000320193-18-000072',
    '0001193125-18-154515',
    '0000320193-18-000070',
    '0000320193-18-000067',
    '0000320193-18-000064',
    '0000320193-18-000063',
    '0000320193-18-000060',
    '0000320193-18-000058',
    '0000320193-18-000057',
    '0000320193-18-000054',
    '0000320193-18-000053',
    '0000320193-18-000052',
    '0000320193-18-000051',
    '0000320193-18-000050',
    '0000320193-18-000049',
    '0000320193-18-000048',
    '0001193125-18-073716',
    '0000320193-18-000040',
    '0000320193-18-000037',
    '0000320193-18-000036',
    '0000320193-18-000035',
    '0000320193-18-000034',
    '0000320193-18-000033',
    '0000320193-18-000032',
    '0000320193-18-000031',
    '0001193125-18-045761',
    '0000932471-18-004625',
    '0000320193-18-000023',
    '0000320193-18-000021',
    '0000320193-18-000020',
    '0000320193-18-000019',
    '0000320193-18-000018',
    '0000320193-18-000017',
    '0000320193-18-000016',
    '0000320193-18-000015',
    '0000320193-18-000007',
    '0000320193-18-000005',
    '0000215457-18-003762',
    '0000320193-18-000002',
    '0001193125-17-380132',
    '0001193125-17-380130',
    '0000320193-17-000087',
    '0000320193-17-000085',
    '0000320193-17-000083',
    '0000320193-17-000081',
    '0000320193-17-000079',
    '0000320193-17-000078',
    '0000320193-17-000077',
    '0001193125-17-341015',
    '0001193125-17-335805',
    '0001193125-17-334724',
    '0001193125-17-333582',
    '0000320193-17-000070',
    '0000320193-17-000067',
    '0000320193-17-000063',
    '0000320193-17-000062',
    '0000320193-17-000061',
    '0000320193-17-000060',
    '0000320193-17-000059',
    '0000320193-17-000058',
    '0000320193-17-000057',
    '0000320193-17-000056',
    '0000320193-17-000055',
    '0001193125-17-308859',
    '0000320193-17-000045',
    '0000320193-17-000043',
    '0000320193-17-000042',
    '0000320193-17-000039',
    '0000320193-17-000038',
    '0000320193-17-000037',
    '0000320193-17-000036',
    '0000320193-17-000035',
    '0000320193-17-000034',
    '0000320193-17-000033',
    '0000320193-17-000032',
    '0001193125-17-282809',
    '0001193125-17-277897',
    '0001193125-17-276961',
    '0001193125-17-276117',
    '0000320193-17-000023',
    '0000320193-17-000021',
    '0000320193-17-000018',
    '0001193125-17-262261',
    '0000320193-17-000017',
    '0001193125-17-258933',
    '0001193125-17-258729',
    '0001193125-17-258040',
    '0000320193-17-000015',
    '0000320193-17-000014',
    '0000320193-17-000013',
    '0000320193-17-000009',
    '0000320193-17-000006',
    '0000320193-17-000003',
    '0001193125-17-208226',
    '0001628280-17-006558',
    '0001193125-17-203548',
    '0001193125-17-202772',
    '0001193125-17-201958',
    '0001628280-17-006357',
    '0001628280-17-006261',
    '0001628280-17-006119',
    '0001628280-17-006040',
    '0001628280-17-005932',
    '9999999997-17-006550',
    '0001628280-17-005877',
    '0001628280-17-005876',
    '0001193125-17-181871',
    '0001193125-17-181867',
    '0001628280-17-005698',
    '0001193125-17-175330',
    '0001193125-17-173678',
    '0001193125-17-172693',
    '0001628280-17-005434',
    '0001628280-17-005433',
    '0001193125-17-167400',
    '0001628280-17-005184',
    '0001628280-17-005183',
    '0001193125-17-160948',
    '0001193125-17-159397',
    '0001193125-17-159324',
    '0001193125-17-157385',
    '0001628280-17-004826',
    '0001628280-17-004790',
    '0001628280-17-004663',
    '0001628280-17-004167',
    '0001628280-17-003836',
    '0001628280-17-003835',
    '0001628280-17-003834',
    '0001628280-17-003444',
    '0001628280-17-003442',
    '0001628280-17-003348',
    '0001628280-17-003347',
    '0001628280-17-003346',
    '0001628280-17-003345',
    '0001628280-17-003344',
    '0001628280-17-003343',
    '0001628280-17-003342',
    '0001628280-17-003341',
    '0001628280-17-002692',
    '0001628280-17-002321',
    '0001193125-17-069853',
    '0001628280-17-002133',
    '0001628280-17-002132',
    '0001628280-17-002131',
    '0001628280-17-002130',
    '0001628280-17-002129',
    '0001628280-17-002128',
    '0001628280-17-002127',
    '0001193125-17-064019',
    '0001628280-17-001737',
    '0001628280-17-001593',
    '0001628280-17-001484',
    '0001628280-17-001483',
    '0001193125-17-044564',
    '0001193125-17-042083',
    '0001193125-17-041233',
    '0001193125-17-036283',
    '0000932471-17-000777',
    '0001628280-17-000963',
    '0001628280-17-000897',
    '0001628280-17-000896',
    '0001628280-17-000895',
    '0001628280-17-000894',
    '0001628280-17-000893',
    '0001628280-17-000892',
    '0001628280-17-000891',
    '0001628280-17-000890',
    '0001628280-17-000889',
    '0001628280-17-000888',
    '0001193125-17-030832',
    '0001193125-17-029548',
    '0001193125-17-028315',
    '0001628280-17-000744',
    '0001628280-17-000717',
    '0001628280-17-000663',
    '0001214659-17-000547',
    '0001628280-17-000550',
    '0001628280-17-000379',
    '0001628280-17-000312',
    '0001628280-17-000311',
    '0000215457-17-001275',
    '0001628280-17-000187',
    '0001193125-17-003764',
    '0001193125-17-003753',
    '0001628280-16-022242',
    '0001628280-16-022104',
    '0001628280-16-022047',
    '0001628280-16-022020',
    '9999999997-17-000002',
    '0001628280-16-021649',
    '0001628280-16-021144',
    '0001628280-16-020880',
    '0001628280-16-020879',
    '0001628280-16-020489',
    '0001628280-16-020488',
    '9999999997-17-000809',
    '9999999997-16-026607',

In [44]:
edgar.get_company_facts(cik="320193")

{'cik': 320193,
 'entityName': 'Apple Inc.',
 'facts': {'dei': {'EntityCommonStockSharesOutstanding': {'label': 'Entity Common Stock, Shares Outstanding',
    'description': "Indicate number of shares or other units outstanding of each of registrant's classes of capital or common stock or other ownership interests, if and as stated on cover of related periodic report. Where multiple classes or units exist define each class/interest by adding class of stock items such as Common Class A [Member], Common Class B [Member] or Partnership Interest [Member] onto the Instrument [Domain] of the Entity Listings, Instrument.",
    'units': {'shares': [{'end': '2009-06-27',
       'val': 895816758,
       'accn': '0001193125-09-153165',
       'fy': 2009,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2009-07-22',
       'frame': 'CY2009Q2I'},
      {'end': '2009-10-16',
       'val': 900678473,
       'accn': '0001193125-09-214859',
       'fy': 2009,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2009-10-27'},
      {'end': '2009-10-16',
       'val': 900678473,
       'accn': '0001193125-10-012091',
       'fy': 2009,
       'fp': 'FY',
       'form': '10-K/A',
       'filed': '2010-01-25',
       'frame': 'CY2009Q3I'},
      {'end': '2010-01-15',
       'val': 906794589,
       'accn': '0001193125-10-012085',
       'fy': 2010,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2010-01-25',
       'frame': 'CY2009Q4I'},
      {'end': '2010-04-09',
       'val': 909938383,
       'accn': '0001193125-10-088957',
       'fy': 2010,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2010-04-21',
       'frame': 'CY2010Q1I'},
      {'end': '2010-07-09',
       'val': 913562880,
       'accn': '0001193125-10-162840',
       'fy': 2010,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2010-07-21',
       'frame': 'CY2010Q2I'},
      {'end': '2010-10-15',
       'val': 917307099,
       'accn': '0001193125-10-238044',
       'fy': 2010,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2010-10-27',
       'frame': 'CY2010Q3I'},
      {'end': '2011-01-07',
       'val': 921278012,
       'accn': '0001193125-11-010144',
       'fy': 2011,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2011-01-19',
       'frame': 'CY2010Q4I'},
      {'end': '2011-04-08',
       'val': 924754561,
       'accn': '0001193125-11-104388',
       'fy': 2011,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2011-04-21',
       'frame': 'CY2011Q1I'},
      {'end': '2011-07-08',
       'val': 927090886,
       'accn': '0001193125-11-192493',
       'fy': 2011,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2011-07-20',
       'frame': 'CY2011Q2I'},
      {'end': '2011-10-14',
       'val': 929409000,
       'accn': '0001193125-11-282113',
       'fy': 2011,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2011-10-26',
       'frame': 'CY2011Q3I'},
      {'end': '2012-01-13',
       'val': 932370000,
       'accn': '0001193125-12-023398',
       'fy': 2012,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2012-01-25',
       'frame': 'CY2011Q4I'},
      {'end': '2012-04-13',
       'val': 935062000,
       'accn': '0001193125-12-182321',
       'fy': 2012,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2012-04-25',
       'frame': 'CY2012Q1I'},
      {'end': '2012-07-13',
       'val': 937406000,
       'accn': '0001193125-12-314552',
       'fy': 2012,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2012-07-25',
       'frame': 'CY2012Q2I'},
      {'end': '2012-10-19',
       'val': 940692000,
       'accn': '0001193125-12-444068',
       'fy': 2012,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2012-10-31',
       'frame': 'CY2012Q3I'},
      {'end': '2013-01-11',
       'val': 939058000,
       'accn': '0001193125-13-022339',
       'fy': 2013,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2013-01-24',
       'frame': 'CY2012Q4I'},
      {'end': '2013-04-12',
       'val': 938649000,
       'accn': '0001193125-13-168288',
       'fy': 2013,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2013-04-24',
       'frame': 'CY2013Q1I'},
      {'end': '2013-07-12',
       'val': 908497000,
       'accn': '0001193125-13-300670',
       'fy': 2013,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2013-07-24',
       'frame': 'CY2013Q2I'},
      {'end': '2013-10-18',
       'val': 899738000,
       'accn': '0001193125-13-416534',
       'fy': 2013,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2013-10-30',
       'frame': 'CY2013Q3I'},
      {'end': '2014-01-10',
       'val': 891989000,
       'accn': '0001193125-14-024487',
       'fy': 2014,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2014-01-28',
       'frame': 'CY2013Q4I'},
      {'end': '2014-04-11',
       'val': 861381000,
       'accn': '0001193125-14-157311',
       'fy': 2014,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2014-04-24',
       'frame': 'CY2014Q1I'},
      {'end': '2014-07-11',
       'val': 5987867000,
       'accn': '0001193125-14-277160',
       'fy': 2014,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2014-07-23',
       'frame': 'CY2014Q2I'},
      {'end': '2014-10-10',
       'val': 5864840000,
       'accn': '0001193125-14-383437',
       'fy': 2014,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2014-10-27',
       'frame': 'CY2014Q3I'},
      {'end': '2015-01-09',
       'val': 5824748000,
       'accn': '0001193125-15-023697',
       'fy': 2015,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2015-01-28',
       'frame': 'CY2014Q4I'},
      {'end': '2015-04-10',
       'val': 5761030000,
       'accn': '0001193125-15-153166',
       'fy': 2015,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2015-04-28',
       'frame': 'CY2015Q1I'},
      {'end': '2015-07-10',
       'val': 5702722000,
       'accn': '0001193125-15-259935',
       'fy': 2015,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2015-07-22',
       'frame': 'CY2015Q2I'},
      {'end': '2015-10-09',
       'val': 5575331000,
       'accn': '0001193125-15-356351',
       'fy': 2015,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2015-10-28',
       'frame': 'CY2015Q3I'},
      {'end': '2016-01-08',
       'val': 5544583000,
       'accn': '0001193125-16-439878',
       'fy': 2016,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2016-01-27',
       'frame': 'CY2015Q4I'},
      {'end': '2016-04-08',
       'val': 5477425000,
       'accn': '0001193125-16-559625',
       'fy': 2016,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2016-04-27',
       'frame': 'CY2016Q1I'},
      {'end': '2016-07-15',
       'val': 5388443000,
       'accn': '0001628280-16-017809',
       'fy': 2016,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2016-07-27',
       'frame': 'CY2016Q2I'},
      {'end': '2016-10-14',
       'val': 5332313000,
       'accn': '0001628280-16-020309',
       'fy': 2016,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2016-10-26',
       'frame': 'CY2016Q3I'},
      {'end': '2017-01-20',
       'val': 5246540000,
       'accn': '0001628280-17-000717',
       'fy': 2017,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2017-02-01',
       'frame': 'CY2016Q4I'},
      {'end': '2017-04-21',
       'val': 5213840000,
       'accn': '0001628280-17-004790',
       'fy': 2017,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2017-05-03',
       'frame': 'CY2017Q1I'},
      {'end': '2017-07-21',
       'val': 5165228000,
       'accn': '0000320193-17-000009',
       'fy': 2017,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2017-08-02',
       'frame': 'CY2017Q2I'},
      {'end': '2017-10-20',
       'val': 5134312000,
       'accn': '0000320193-17-000070',
       'fy': 2017,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2017-11-03',
       'frame': 'CY2017Q3I'},
      {'end': '2018-01-19',
       'val': 5074013000,
       'accn': '0000320193-18-000007',
       'fy': 2018,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2018-02-02',
       'frame': 'CY2017Q4I'},
      {'end': '2018-04-20',
       'val': 4915138000,
       'accn': '0000320193-18-000070',
       'fy': 2018,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2018-05-02',
       'frame': 'CY2018Q1I'},
      {'end': '2018-07-20',
       'val': 4829926000,
       'accn': '0000320193-18-000100',
       'fy': 2018,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2018-08-01',
       'frame': 'CY2018Q2I'},
      {'end': '2018-10-26',
       'val': 4745398000,
       'accn': '0000320193-18-000145',
       'fy': 2018,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2018-11-05',
       'frame': 'CY2018Q3I'},
      {'end': '2019-01-18',
       'val': 4715280000,
       'accn': '0000320193-19-000010',
       'fy': 2019,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2019-01-30',
       'frame': 'CY2018Q4I'},
      {'end': '2019-04-22',
       'val': 4601075000,
       'accn': '0000320193-19-000066',
       'fy': 2019,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2019-05-01',
       'frame': 'CY2019Q1I'},
      {'end': '2019-07-19',
       'val': 4519180000,
       'accn': '0000320193-19-000076',
       'fy': 2019,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2019-07-31',
       'frame': 'CY2019Q2I'},
      {'end': '2019-10-18',
       'val': 4443265000,
       'accn': '0000320193-19-000119',
       'fy': 2019,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2019-10-31',
       'frame': 'CY2019Q3I'},
      {'end': '2020-01-17',
       'val': 4375480000,
       'accn': '0000320193-20-000010',
       'fy': 2020,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2020-01-29',
       'frame': 'CY2019Q4I'},
      {'end': '2020-04-17',
       'val': 4334335000,
       'accn': '0000320193-20-000052',
       'fy': 2020,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2020-05-01',
       'frame': 'CY2020Q1I'},
      {'end': '2020-07-17',
       'val': 4275634000,
       'accn': '0000320193-20-000062',
       'fy': 2020,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2020-07-31',
       'frame': 'CY2020Q2I'},
      {'end': '2020-10-16',
       'val': 17001802000,
       'accn': '0000320193-20-000096',
       'fy': 2020,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2020-10-30',
       'frame': 'CY2020Q3I'},
      {'end': '2021-01-15',
       'val': 16788096000,
       'accn': '0000320193-21-000010',
       'fy': 2021,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2021-01-28',
       'frame': 'CY2020Q4I'},
      {'end': '2021-04-16',
       'val': 16687631000,
       'accn': '0000320193-21-000056',
       'fy': 2021,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2021-04-29',
       'frame': 'CY2021Q1I'},
      {'end': '2021-07-16',
       'val': 16530166000,
       'accn': '0000320193-21-000065',
       'fy': 2021,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2021-07-28',
       'frame': 'CY2021Q2I'},
      {'end': '2021-10-15',
       'val': 16406397000,
       'accn': '0000320193-21-000105',
       'fy': 2021,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2021-10-29',
       'frame': 'CY2021Q3I'},
      {'end': '2022-01-14',
       'val': 16319441000,
       'accn': '0000320193-22-000007',
       'fy': 2022,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2022-01-28',
       'frame': 'CY2021Q4I'},
      {'end': '2022-04-15',
       'val': 16185181000,
       'accn': '0000320193-22-000059',
       'fy': 2022,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2022-04-29',
       'frame': 'CY2022Q1I'},
      {'end': '2022-07-15',
       'val': 16070752000,
       'accn': '0000320193-22-000070',
       'fy': 2022,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2022-07-29',
       'frame': 'CY2022Q2I'},
      {'end': '2022-10-14',
       'val': 15908118000,
       'accn': '0000320193-22-000108',
       'fy': 2022,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2022-10-28',
       'frame': 'CY2022Q3I'},
      {'end': '2023-01-20',
       'val': 15821946000,
       'accn': '0000320193-23-000006',
       'fy': 2023,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2023-02-03',
       'frame': 'CY2022Q4I'},
      {'end': '2023-04-21',
       'val': 15728702000,
       'accn': '0000320193-23-000064',
       'fy': 2023,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2023-05-05',
       'frame': 'CY2023Q1I'},
      {'end': '2023-07-21',
       'val': 15634232000,
       'accn': '0000320193-23-000077',
       'fy': 2023,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2023-08-04',
       'frame': 'CY2023Q2I'},
      {'end': '2023-10-20',
       'val': 15552752000,
       'accn': '0000320193-23-000106',
       'fy': 2023,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2023-11-03',
       'frame': 'CY2023Q3I'},
      {'end': '2024-01-19',
       'val': 15441881000,
       'accn': '0000320193-24-000006',
       'fy': 2024,
       'fp': 'Q1',
       'form': '10-Q',
       'filed': '2024-02-02',
       'frame': 'CY2023Q4I'},
      {'end': '2024-04-19',
       'val': 15334082000,
       'accn': '0000320193-24-000069',
       'fy': 2024,
       'fp': 'Q2',
       'form': '10-Q',
       'filed': '2024-05-03',
       'frame': 'CY2024Q1I'},
      {'end': '2024-07-19',
       'val': 15204137000,
       'accn': '0000320193-24-000081',
       'fy': 2024,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2024-08-02',
       'frame': 'CY2024Q2I'}]}},
   'EntityPublicFloat': {'label': 'Entity Public Float',
    'description': "The aggregate market value of the voting and non-voting common equity held by non-affiliates computed by reference to the price at which the common equity was last sold, or the average bid and asked price of such common equity, as of the last business day of the registrant's most recently completed second fiscal quarter.",
    'units': {'USD': [{'end': '2009-03-28',
       'val': 94593000000,
       'accn': '0001193125-09-153165',
       'fy': 2009,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2009-07-22'},
      {'end': '2009-03-28',
       'val': 94593000000,
       'accn': '0001193125-09-214859',
       'fy': 2009,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2009-10-27'},
      {'end': '2009-03-28',
       'val': 94593000000,
       'accn': '0001193125-10-012091',
       'fy': 2009,
       'fp': 'FY',
       'form': '10-K/A',
       'filed': '2010-01-25',
       'frame': 'CY2009Q1I'},
      {'end': '2010-03-27',
       'val': 208565000000,
       'accn': '0001193125-10-238044',
       'fy': 2010,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2010-10-27',
       'frame': 'CY2010Q1I'},
      {'end': '2011-03-25',
       'val': 322921000000,
       'accn': '0001193125-11-282113',
       'fy': 2011,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2011-10-26',
       'frame': 'CY2011Q1I'},
      {'end': '2012-03-30',
       'val': 560356000000,
       'accn': '0001193125-12-444068',
       'fy': 2012,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2012-10-31',
       'frame': 'CY2012Q1I'},
      {'end': '2013-03-29',
       'val': 416005000000,
       'accn': '0001193125-13-416534',
       'fy': 2013,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2013-10-30',
       'frame': 'CY2013Q1I'},
      {'end': '2014-03-28',
       'val': 462522000000,
       'accn': '0001193125-14-383437',
       'fy': 2014,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2014-10-27',
       'frame': 'CY2014Q1I'},
      {'end': '2015-03-27',
       'val': 709923000000,
       'accn': '0001193125-15-356351',
       'fy': 2015,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2015-10-28',
       'frame': 'CY2015Q1I'},
      {'end': '2016-03-25',
       'val': 578807000000,
       'accn': '0001628280-16-020309',
       'fy': 2016,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2016-10-26',
       'frame': 'CY2016Q1I'},
      {'end': '2017-03-31',
       'val': 747509000000,
       'accn': '0000320193-17-000070',
       'fy': 2017,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2017-11-03',
       'frame': 'CY2017Q1I'},
      {'end': '2018-03-30',
       'val': 828880000000,
       'accn': '0000320193-18-000145',
       'fy': 2018,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2018-11-05',
       'frame': 'CY2018Q1I'},
      {'end': '2019-03-29',
       'val': 874698000000,
       'accn': '0000320193-19-000119',
       'fy': 2019,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2019-10-31',
       'frame': 'CY2019Q1I'},
      {'end': '2020-03-27',
       'val': 1070633000000,
       'accn': '0000320193-20-000096',
       'fy': 2020,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2020-10-30',
       'frame': 'CY2020Q1I'},
      {'end': '2021-03-26',
       'val': 2021360000000,
       'accn': '0000320193-21-000105',
       'fy': 2021,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2021-10-29',
       'frame': 'CY2021Q1I'},
      {'end': '2022-03-25',
       'val': 2830067000000,
       'accn': '0000320193-22-000108',
       'fy': 2022,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2022-10-28',
       'frame': 'CY2022Q1I'},
      {'end': '2023-03-31',
       'val': 2591165000000,
       'accn': '0000320193-23-000106',
       'fy': 2023,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2023-11-03',
       'frame': 'CY2023Q1I'}]}}},
  'us-gaap': {'AccountsPayable': {'label': 'Accounts Payable (Deprecated 2009-01-31)',
    'description': "Carrying value as of the balance sheet date of liabilities incurred (and for which invoices have typically been received) and payable to vendors for goods and services received that are used in an entity's business. For classified balance sheets, used to reflect the current portion of the liabilities (due within one year or within the normal operating cycle if longer); for unclassified balance sheets, used to reflect the total liabilities (regardless of due date).",
    'units': {'USD': [{'end': '2008-09-27',
       'val': 5520000000,
       'accn': '0001193125-09-153165',
       'fy': 2009,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2009-07-22',
       'frame': 'CY2008Q3I'},
      {'end': '2009-06-27',
       'val': 4854000000,
       'accn': '0001193125-09-153165',
       'fy': 2009,
       'fp': 'Q3',
       'form': '10-Q',
       'filed': '2009-07-22',
       'frame': 'CY2009Q2I'}]}},
   'AccountsPayableCurrent': {'label': 'Accounts Payable, Current',
    'description': "Carrying value as of the balance sheet date of liabilities incurred (and for which invoices have typically been received) and payable to vendors for goods and services received that are used in an entity's business. Used to reflect the current portion of the liabilities (due within one year or within the normal operating cycle if longer).",
    'units': {'USD': [{'end': '2008-09-27',
       'val': 5520000000,
       'accn': '0001193125-09-214859',
       'fy': 2009,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2009-10-27'},
      {'end': '2008-09-27',
       'val': 5520000000,
       'accn': '0001193125-10-012091',
       'fy': 2009,
       'fp': 'FY',
       'form': '10-K/A',
       'filed': '2010-01-25',
       'frame': 'CY2008Q3I'},
      {'end': '2009-09-26',
       'val': 5601000000,
       'accn': '0001193125-09-214859',
       'fy': 2009,
       'fp': 'FY',
       'form': '10-K',
       'filed': '2009-10-27'},